### ISSUE TITLE
Uncaught TypeError: Cannot read property 'file' of undefined

### ISSUE THREAD

**Issue by sakoh** [facebook-atom/atom-ide-ui#113]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.2 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.5.3

### Stack Trace

Uncaught TypeError: Cannot read property 'file' of undefined

```
At /Users/sakohartounian/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:23

TypeError: Cannot read property 'file' of undefined
    at linterMessageV2ToDiagnosticMessage (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-diagnostics/lib/services/LinterAdapter.js:180:27)
    at linterMessagesToDiagnosticUpdate (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-diagnostics/lib/services/LinterAdapter.js:199:56)
    at /packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-diagnostics/lib/services/LinterAdapter.js:264:22)
    at a._next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:238:504)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:64)
    at a.notifyNext (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:60:68)
    at a._next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:61:263)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:64)
    at /packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:23:256
```

### Commands

```
```

### Non-Core Packages

```
angularjs 0.4.0 
atom-bemmet 2.0.0 
atom-handlebars 1.3.0 
atom-ide-ui 0.5.3 
atom-jade 0.3.0 
atom-jinja2 0.6.0 
atom-liquid-snippets 0.3.0 
atom-sugarml 0.2.0 
atom-typescript 11.0.10 
autoclose-html 0.23.0 
better-handlebars 0.1.1 
busy-signal 1.4.3 
editorconfig 2.2.2 
elm-format 3.0.0 
emmet 2.4.3 
emmet-simplified 2.5.0 
emmet-snippets-compatibility 1.0.6 
file-types 0.5.5 
flow-ide 1.9.0 
hyperclick 0.0.0 
ide-go 0.4.0 
ide-html 0.4.1 
ide-vue 0.1.7 
intentions 1.1.5 
javascript-snippets 1.2.1 
language-ace 1.1.0 
language-blade 0.36.0 
language-cjsx 0.3.0 
language-ejs 0.4.0 
language-elixir 0.20.3 
language-elm 1.5.0 
language-gherkin 1.0.4 
language-handlebars 0.2.0 
language-javascript-jsx 0.3.7 
language-jsont 0.3.0 
language-liquid 0.6.0 
language-vue 0.23.1 
laravel 0.7.1 
linter 2.2.0 
linter-elm-make 0.26.2 
linter-ui-default 1.6.10 
lipsum 0.1.0 
merge-conflicts 1.4.5 
php-twig 4.0.0 
Sublime-Style-Column-Selection 1.7.4 
```

**Comment by hansonw** [comment]
Is this still an issue? Closing due to age
