### ISSUE TITLE
Uncaught TypeError: Cannot read property 'lineTiles' of undefined

### ISSUE THREAD

**Issue by ssanusi** [facebook-atom/atom-ide-ui#114]
[Before submitting, please enter steps to reproduce:]

1. ...
2. ...

**Learn IDE Package**: 2.5.3
**Learn IDE Core**: 2.5.1 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.13
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.5.4

### Stack Trace

Uncaught TypeError: Cannot read property 'lineTiles' of undefined

```
At /Users/sscode/.atom/packages/atom-ide-ui/modules/atom-ide-ui/pkg/hyperclick/lib/HyperclickForTextEditor.js:121

TypeError: Cannot read property 'lineTiles' of undefined
    at addMouseListeners (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/hyperclick/lib/HyperclickForTextEditor.js:121:42)
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:141:28)
    at /app.asar/src/text-editor-element.js:91:27)
    at /app.asar/src/pane-element.js:138:24)
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:141:28)
    at Pane.module.exports.Pane.setActiveItem (/app.asar/src/pane.js:300:22)
    at Pane.module.exports.Pane.addItem (/app.asar/src/pane.js:515:14)
    at Pane.module.exports.Pane.activateItem (/app.asar/src/pane.js:449:14)
    at /app.asar/src/workspace.js:545:18
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-ui 0.5.4 
atom-quokka 1.0.19 
cobalt2-syntax 0.5.1 
```

**Comment by hansonw** [comment]
Hey - It looks like you're on a very old version of Atom (the most recent
stable is 1.21.2).
Please download a new one from
https://github.com/atom/atom/releases/tag/v1.21.2, thanks!
