### ISSUE TITLE
Uncaught Error: EIO: i/o error, write

### ISSUE THREAD

**Issue by guillehampp** [facebook-atom/atom-ide-ui#117]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.0 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.04.3
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.5.4

### Stack Trace

Uncaught Error: EIO: i/o error, write

```
At /home/guillermo/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:23

Error: EIO: i/o error, write
    at Object.fs.writeSync (fs.js:719:20)
    at SyncWriteStream._write (internal/fs.js:75:6)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at SyncWriteStream.Writable.write (_stream_writable.js:245:11)
    at /packages/atom-ide-ui/node_modules/log4js/lib/appenders/stdout.js:8:20)
    at emitOne (events.js:96:13)
    at Logger.emit (events.js:188:7)
    at Logger._log (/packages/atom-ide-ui/node_modules/log4js/lib/logger.js:96:8)
    at /packages/atom-ide-ui/node_modules/log4js/lib/logger.js:89:12)
    at Promise.resolve.catch.error (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-diagnostics/lib/services/LinterAdapter.js:258:76)
```

### Commands

```
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.30.6 
atom-clock 0.1.15 
atom-ide-ui 0.5.4 
autocomplete-php 0.3.7 
busy-signal 1.4.3 
hyperclick 0.0.0 
ide-php 0.6.10 
intentions 1.1.5 
language-vue 0.23.1 
laravel 0.7.1 
laravel-5-snippets 0.19.0 
laravel-forms-bootstrap-snippets 1.2.0 
laravel-snippets 2.1.0 
linter 2.2.0 
linter-php 1.5.1 
linter-ui-default 1.6.10 
php-cs-fixer 4.1.1 
php-debug 0.2.5 
php-integrator-autocomplete-plus 1.6.1 
php-integrator-base 3.1.0 
php-integrator-call-tips-legacy-php56 1.2.3 
php-integrator-navigation 1.2.1 
php-integrator-refactoring 1.4.1 
project-manager 3.3.5 
```

**Comment by buzz** [comment]
[Enter steps to reproduce:]

1. Download atom
2. Install packages
3. File -> Open folder

**Atom**: 1.33.0 x64
**Electron**: 2.0.11
**OS**: "openSUSE Leap
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.13.0


### Stack Trace

Uncaught Error: EIO: i/o error, write

```
At /store/cosmetix/datastore/dietrich/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:34

Error: EIO: i/o error, write
    at Object.fs.writeSync (fs.js:735:20)
    at SyncWriteStream._write (internal/fs.js:74:6)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at SyncWriteStream.Writable.write (_stream_writable.js:290:11)
    at /packages/atom-ide-ui/node_modules/log4js/lib/appenders/stdout.js:8:20)
    at emitOne (events.js:116:13)
    at Logger.emit (events.js:211:7)
    at Logger._log (/packages/atom-ide-ui/node_modules/log4js/lib/logger.js:96:8)
    at /packages/atom-ide-ui/node_modules/log4js/lib/logger.js:89:12)
    at CodeHighlightManager._getHighlightedRanges (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-code-highlight/lib/CodeHighlightManager.js:137:50)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-debugger-python 0.7.3 
atom-ide-ui 0.13.0 
busy-signal 1.4.3 
color-picker 2.3.0 
editorconfig 2.2.2 
file-icons 2.1.26 
highlight-selected 0.14.0 
ide-python 1.1.0 
ide-typescript 0.8.0 
intentions 1.1.5 
language-docker 1.1.8 
language-restructuredtext 1.1.2 
linter 2.2.0 
linter-eslint 8.4.1 
linter-flake8 2.3.0 
linter-pylint 2.1.1 
linter-ui-default 1.7.1 
markdown-preview-enhanced 0.15.8 
project-manager 3.3.6 
react 0.18.0 
sort-lines 0.18.0 
updater-notify 1.2.0 
```
