### ISSUE TITLE
Uncaught Error: Cannot find module 'nuclide-commons/event'

### ISSUE THREAD

**Issue by elultimocapo421** [facebook-atom/atom-ide-ui#119]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.0 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.5.4

### Stack Trace

Uncaught Error: Cannot find module 'nuclide-commons/event'

```
At C:\Users\reymy\.atom\packages\atom-ide-ui\node_modules\rxjs\bundles\Rx.min.js:43

Error: Cannot find module 'nuclide-commons/event'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.22.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.22.0/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.22.0/resources/app/src/native-compile-cache.js:66:33)
    at _load_event (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-code-actions/lib/CodeActionManager.js:51:19)
    at /packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-code-actions/lib/CodeActionManager.js:145:44)
    at a._next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:238:504)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:64)
    at a._next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:106:294)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:64)
    at a.x (/packages/atom-ide-ui/modules/nuclide-commons/observable.js:340:86)
    at later (/packages/atom-ide-ui/modules/nuclide-commons/debounce.js:27:23)
```

### Commands

```
     -8:12.4.0 core:backspace (input.hidden-input)
     -8:11.1.0 core:confirm (input.hidden-input)
 35x -7:51.9.0 core:move-down (div.package-detail.panels-item)
     -5:07.3.0 application:add-project-folder (input.hidden-input)
  2x -3:23.5.0 core:move-down (input.hidden-input)
     -3:22.4.0 core:move-up (input.hidden-input)
     -3:21.7.0 core:backspace (input.hidden-input)
     -2:41.7.0 github:view-staged-changes-for-current-file (div.line.cursor-line)
  4x -2:27 editor:move-to-end-of-screen-line (input.hidden-input)
  7x -2:22.6.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.5.4 
atom-live-server 2.2.0 
color-picker 2.2.5 
ide-php 0.6.10 
```

**Comment by hansonw** [comment]
Please see https://github.com/facebook-atom/atom-ide-ui/issues/64 for
instructions on how to resolve this.
