### ISSUE TITLE
Uncaught TypeError: null is not iterable

### ISSUE THREAD

**Issue by karazi** [facebook-atom/atom-ide-ui#120]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.0 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.5.4

### Stack Trace

Uncaught TypeError: null is not iterable

```
At /Users/elyakimkarazi/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:69

TypeError: null is not iterable
    at arrayFlatten (/packages/atom-ide-ui/modules/nuclide-commons/collection.js:100:20)
    at /packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-code-actions/lib/CodeActionManager.js:119:67
    at Generator.next (<anonymous>)
    at step (/packages/atom-ide-ui/node_modules/async-to-generator/async-to-generator.js:11:30)
    at _next (/packages/atom-ide-ui/node_modules/async-to-generator/async-to-generator.js:24:9)
```

### Commands

```
     -0:36.8.0 tabs:close-all-tabs (div.title.icon.elixir-icon.dark-purple)
  2x -0:14.4.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.6 
atom-elixir 0.2.3 
atom-ide-ui 0.5.4 
ctrl-last-tab 0.3.0 
file-icons 2.1.13 
ide-elixir 0.2.2 
language-elixir 0.20.3 
markdown-table-editor 0.6.4 
platformio-ide-terminal 2.7.0 
```

**Comment by hansonw** [comment]
Will be fixed in (soon to be released) v0.6.0.
