### ISSUE TITLE
Uncaught Error: Debug Failure. 

### ISSUE THREAD

**Issue by JacobDFrank** [facebook-atom/atom-ide-ui#130]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.2
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.6.0

### Stack Trace

Uncaught Error: Debug Failure. 

```
At /Users/jacobfrank/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:69

Error: Debug Failure. 
    at /packages/ide-php/node_modules/vscode-jsonrpc/lib/messages.js:46:28)
    at handleResponse (/packages/ide-php/node_modules/vscode-jsonrpc/lib/main.js:430:48)
    at processMessageQueue (/packages/ide-php/node_modules/vscode-jsonrpc/lib/main.js:258:17)
    at /packages/ide-php/node_modules/vscode-jsonrpc/lib/main.js:242:13)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

### Commands

```
  3x -0:38.1.0 core:undo (input.hidden-input)
  2x -0:34.9.0 core:backspace (input.hidden-input)
     -0:34 core:move-down (input.hidden-input)
  2x -0:33.5.0 editor:newline (input.hidden-input)
     -0:32.6.0 core:move-up (input.hidden-input)
     -0:32.3.0 core:backspace (input.hidden-input)
  2x -0:31.6.0 editor:newline (input.hidden-input)
     -0:31.1.0 core:paste (input.hidden-input)
     -0:22 core:move-left (input.hidden-input)
     -0:14.8.0 core:move-right (input.hidden-input)
     -0:14.5.0 core:backspace (input.hidden-input)
  5x -0:14.1.0 core:move-left (input.hidden-input)
     -0:13 core:backspace (input.hidden-input)
  5x -0:12.6.0 core:select-right (input.hidden-input)
     -0:08.8.0 core:undo (input.hidden-input)
     -0:07.1.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-alignment 0.13.0 
atom-beautify 0.30.9 
atom-ide-ui 0.6.0 
browser-plus 0.0.98 
busy-signal 1.4.3 
change-case 0.6.5 
city-lights-icons 1.1.1 
city-lights-syntax 1.1.4 
city-lights-ui 1.2.0 
color-picker 2.2.5 
emmet 2.4.3 
emmet 2.4.3 
git-time-machine 1.5.9 
ide-typescript 0.7.1 
intentions 1.1.5 
jshint 1.8.6 
language-babel 2.80.3 
language-glsl 2.0.4 
language-graphql 0.9.0 
language-lua 0.9.11 
language-nunjucks 4.2.1 
language-sql-mysql 0.3.1 
linter 2.2.0 
linter-eslint 8.4.0 
linter-ui-default 1.6.10 
platformio-ide-terminal 2.7.0 
save-workspace 0.4.0 
script 3.18.0 
trailing-spaces 0.4.0 
```

**Comment by hansonw** [comment]
This seems to be an issue purely within the ide-php package - please report it over there instead :)

https://github.com/atom/ide-php/issues

**Comment by lidorcg** [comment]
actually, I'm having it on ide-typescript too...
