### ISSUE TITLE
Uncaught Error: Emitter has been disposed

### ISSUE THREAD

**Issue by mrleblanc101** [facebook-atom/atom-ide-ui#131]
**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.6.0

### Stack Trace

Uncaught Error: Emitter has been disposed

```
At /Users/sleblanc/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:69

Error: Emitter has been disposed
    at Emitter.module.exports.Emitter.on (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:77:21)
    at IndieDelegate.onDidDestroy (/packages/linter/lib/indie-delegate.js:107:25)
    at LinterPushV2Adapter.attach (/packages/ide-php/node_modules/atom-languageclient/build/lib/adapters/linter-push-v2-adapter.js:35:11)
    at TypeScriptLanguageClient.startExclusiveAdapters (/packages/ide-typescript/node_modules/atom-languageclient/build/lib/auto-languageclient.js:352:27)
    at TypeScriptLanguageClient.startServer (/packages/ide-typescript/node_modules/atom-languageclient/build/lib/auto-languageclient.js:291:10)
```

### Commands

```
     -0:55.3.0 find-and-replace:show (input.hidden-input)
     -0:52.2.0 project-find:show (input.hidden-input)
     -0:51.3.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
apex-syntax 0.2.0 
apex-ui 1.0.2 
atom-beautify 0.30.9 
atom-clock 0.1.15 
atom-ide-ui 0.6.0 
atom-material-ui 2.0.6 
atom-typescript 11.0.10 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
busy-signal 1.4.3 
color-picker 2.2.5 
docblockr 0.13.3 
docker 0.8.0 
double-tag 1.1.0 
emmet 2.4.3 
file-icons 2.1.14 
font-preview 0.1.1 
git-diff-details 1.4.0 
hey-pane 1.1.0 
highlight-selected 0.13.1 
ide-php 0.7.3 
ide-typescript 0.7.1 
indent-guide-improved 1.4.13 
intentions 1.1.5 
language-antlers 0.3.4 
language-docker 1.1.8 
lint 0.0.1 
linter 2.2.0 
linter-eslint 8.4.0 
linter-ui-default 1.6.10 
minimap 4.29.7 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
minimap-selection 4.5.0 
minimap-split-diff 0.3.7 
monokai 0.24.0 
multiline-tab 0.2.1 
open-terminal-here 2.3.1 
php-twig 4.0.0 
pigments 0.40.2 
platformio-ide-terminal 2.7.0 
pure-syntax 0.3.0 
simple-drag-drop-text 0.3.6 
split-diff 1.5.1 
svg-preview 0.12.1 
svgo 3.0.0 
sync-settings 0.8.3 
tab-limiter 2.2.0 
tag 0.5.0 
toggler 0.3.0 
tool-bar 1.1.0 
tool-bar-almighty 0.8.2 
tree-view-autoresize 2.3.0 
tree-view-git-branch 0.1.2 
tree-view-scope-lines 0.2.0 
typo3 0.7.0 
```

**Comment by hansonw** [comment]
Hey, this seems to be an interaction between the linter package and atom-languageclient (nothing in the stack trace is atom-ide-ui-related). You might want to file this on atom/atom-languageclient instead :)

**Comment by Arcanemagus** [comment]
@hansonw Atom filed it here because the `rxjs` library being used is coming from `atom-ide-ui`'s `node_modules` 😉.

```
At /Users/sleblanc/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:69
```
