### ISSUE TITLE
Uncaught Error: Expected source file D:/DEV\Repo\XXXXX\www\js\controllers.js to exist in confi...

### ISSUE THREAD

**Issue by wedigitek** [facebook-atom/atom-ide-ui#133]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.0 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.7.0

### Stack Trace

Uncaught Error: Expected source file D:\DEV\Repo\XXXXX\www\js\controllers.js to exist in configuration

```
At C:\Users\eupho\.atom\packages\atom-ide-ui\node_modules\rxjs\bundles\Rx.min.js:69

Error: Expected source file D:\DEV\Repo\XXXXX\www\js\controllers.js to exist in configuration
    at /packages/ide-css/node_modules/vscode-jsonrpc/lib/messages.js:46:28)
    at handleResponse (/packages/ide-html/node_modules/vscode-jsonrpc/lib/main.js:430:48)
    at processMessageQueue (/packages/ide-html/node_modules/vscode-jsonrpc/lib/main.js:258:17)
    at /packages/ide-html/node_modules/vscode-jsonrpc/lib/main.js:242:13)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

### Commands

```
     -0:41.8.0 find-and-replace:show (input.hidden-input)
     -0:36.6.0 core:select-all (input.hidden-input)
  7x -0:35.2.0 core:backspace (input.hidden-input)
     -0:29.1.0 core:confirm (input.hidden-input)
  3x -0:27.9.0 core:backspace (input.hidden-input)
     -0:27.3.0 core:confirm (input.hidden-input)
  4x -0:26.9.0 core:backspace (input.hidden-input)
 10x -0:25.6.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-clock 0.1.15 
atom-ide-ui 0.7.0 
atom-typescript 11.0.10 
atom-visual-studio-code-ui 1.3.4 
autocomplete-ionic-framework 0.2.2 
autocomplete-javascript 0.0.2 
autocomplete-python 1.10.5 
github-atom-light-syntax 0.5.0 
ide-css 0.2.0 
ide-html 0.4.1 
ide-json 0.1.0 
ide-php undefined 
ide-python 0.3.0 
ide-typescript 0.7.2 
ionic-framework-snippets 1.2.1 
ionic-preview 0.7.0 
javascript-refactor 0.6.0 
kite 0.57.0 
language-javascript-jsx 0.3.7 
lazy-light-syntax 0.1.1 
open_in_cmd 0.6.1 
piatto-light-syntax 0.2.2 
pure-syntax 0.3.0 
python-tools 0.6.9 
```

**Comment by shushz** [comment]
Umm.... I think `atom-ide` is only the host, hence taking the blame here. The actual packages mentioned in the stack trace are [ide-html](https://atom.io/packages/ide-html) and [ide-css](https://atom.io/packages/ide-css). Both authored by @liuderchi I'd ask him first.

**Comment by hansonw** [comment]
Yup please file this in one of those repos instead, thanks!
