### ISSUE TITLE
Uncaught Error: Connection got disposed.

### ISSUE THREAD

**Issue by tschaub** [facebook-atom/atom-ide-ui#134]
Hard to say exactly what triggered this.  I've got a "Project Find Results" tab open and I'm doing a lot of tedious manual refactoring - opening, editing, saving, and closing lots of files.

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.7.0

### Stack Trace

Uncaught Error: Connection got disposed.

```
At /Users/tschaub/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:69

Error: Connection got disposed.
    at Object.dispose (/packages/ide-typescript/node_modules/vscode-jsonrpc/lib/main.js:825:25)
    at LanguageClientConnection.dispose (/packages/ide-typescript/node_modules/atom-languageclient/build/lib/languageclient.js:38:15)
    at ServerManager.exitServer (/packages/ide-typescript/node_modules/atom-languageclient/build/lib/server-manager.js:195:25)
    at ServerManager.stopServer (/packages/ide-typescript/node_modules/atom-languageclient/build/lib/server-manager.js:184:12)
```

### Commands

```
     -0:41.2.0 core:save (input.hidden-input)
     -0:40.2.0 core:close (input.hidden-input)
     -0:29.7.0 docblockr:parse-tab (input.hidden-input)
     -0:29.7.0 autocomplete-plus:confirm (input.hidden-input)
     -0:29.2.0 intentions:highlight (input.hidden-input)
     -0:29.1.0 editor:select-to-beginning-of-word (input.hidden-input)
     -0:29 datatip:toggle (input.hidden-input)
     -0:28.7.0 find-and-replace:use-selection-as-find-pattern (input.hidden-input)
     -0:28.5.0 find-and-replace:find-next (input.hidden-input)
     -0:27.7.0 core:move-left (input.hidden-input)
  2x -0:27.3.0 editor:select-to-beginning-of-word (input.hidden-input)
     -0:26.8.0 datatip:toggle (input.hidden-input)
     -0:26.7.0 core:backspace (input.hidden-input)
     -0:25.8.0 find-and-replace:find-next (input.hidden-input)
     -0:24.6.0 core:save (input.hidden-input)
     -0:23.7.0 core:close (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-dark-fusion-syntax 2.2.1 
atom-ide-ui 0.7.0 
atom-import-sort 4.2.0 
busy-signal 1.4.3 
docblockr 0.13.4 
go-debug 1.5.2 
go-plus 5.7.1 
go-signature-statusbar 1.2.3 
hyperclick 0.0.0 
ide-go 0.4.0 
ide-typescript 0.7.2 
intentions 1.1.5 
language-babel 2.81.0 
last-cursor-position 0.9.2 
lines 0.13.1 
linter 2.2.0 
linter-eslint 8.4.0 
linter-ui-default 1.6.10 
nucleus-dark-ui 0.12.3 
pigments 0.40.2 
platformio-ide-terminal 2.7.0 
release-notes 0.53.0 
sync-settings 0.8.3 
```

**Comment by hansonw** [comment]
Could you file this on the https://github.com/atom/ide-typescript issues page instead? Despite the stack trace ending up in Rx this actually seems to be a language client and/or TypeScript server issue, judging by the other entries in the stack. Thanks!

https://github.com/atom/ide-typescript

**Comment by tschaub** [comment]
Thanks @hansonw.  I opened https://github.com/atom/ide-typescript/issues/71 to track this.
