### ISSUE TITLE
Cannot find module 'rxjs/bundles/Rx.min.js'

### ISSUE THREAD

**Issue by chris-martin** [facebook-atom/atom-ide-ui#137]
```
Failed to load the atom-ide-ui package
Cannot find module 'rxjs/bundles/Rx.min.js'

Error: Cannot find module 'rxjs/bundles/Rx.min.js'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/nix/store/kh99mazsn31b0gkjdl99dxgcx5c5x11f-atom-1.23.0/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/nix/store/kh99mazsn31b0gkjdl99dxgcx5c5x11f-atom-1.23.0/share/atom/resources/app/src/module-cache.js:354:58)
    at Module.require (file:///nix/store/kh99mazsn31b0gkjdl99dxgcx5c5x11f-atom-1.23.0/share/atom/resources/app.asar/static/index.js:40:43)
    at require (/nix/store/kh99mazsn31b0gkjdl99dxgcx5c5x11f-atom-1.23.0/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/home/chris/.atom/packages/atom-ide-ui/modules/nuclide-commons-atom/feature-config.js:7:27)
    at Object.<anonymous> (/home/chris/.atom/packages/atom-ide-ui/modules/nuclide-commons-atom/feature-config.js:160:3)
    at Module.get_Module._compile (/nix/store/kh99mazsn31b0gkjdl99dxgcx5c5x11f-atom-1.23.0/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/nix/store/kh99mazsn31b0gkjdl99dxgcx5c5x11f-atom-1.23.0/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///nix/store/kh99mazsn31b0gkjdl99dxgcx5c5x11f-atom-1.23.0/share/atom/resources/app.asar/static/index.js:47:45)
    at require (/nix/store/kh99mazsn31b0gkjdl99dxgcx5c5x11f-atom-1.23.0/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at _load_featureConfig (/home/chris/.atom/packages/atom-ide-ui/modules/nuclide-commons-atom/FeatureLoader.js:16:50)
    at FeatureLoader.load (/home/chris/.atom/packages/atom-ide-ui/modules/nuclide-commons-atom/FeatureLoader.js:130:24)
    at Object.<anonymous> (/home/chris/.atom/packages/atom-ide-ui/index.js:92:17)
    at Object.<anonymous> (/home/chris/.atom/packages/atom-ide-ui/index.js:116:3)
    at Module.get_Module._compile (/nix/store/kh99mazsn31b0gkjdl99dxgcx5c5x11f-atom-1.23.0/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/nix/store/kh99mazsn31b0gkjdl99dxgcx5c5x11f-atom-1.23.0/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///nix/store/kh99mazsn31b0gkjdl99dxgcx5c5x11f-atom-1.23.0/share/atom/resources/app.asar/static/index.js:47:45)
    at require (/nix/store/kh99mazsn31b0gkjdl99dxgcx5c5x11f-atom-1.23.0/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/home/chris/.atom/packages/atom-ide-ui/index-entry.js:29:18)
    at Object.<anonymous> (/home/chris/.atom/packages/atom-ide-ui/index-entry.js:31:3)
    at Module.get_Module._compile (/nix/store/kh99mazsn31b0gkjdl99dxgcx5c5x11f-atom-1.23.0/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/nix/store/kh99mazsn31b0gkjdl99dxgcx5c5x11f-atom-1.23.0/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
```

### Versions
* Atom: 1.23.0
* Client OS: NixOS
* atom-ide-ui: 0.7.0
* ide-haskell-hie 0.7.3

**Comment by hansonw** [comment]
Looks like a bad apm install. Please try:

https://github.com/facebook-atom/atom-ide-ui/issues/64#issuecomment-332980384
