### ISSUE TITLE
Uncaught Error: ENAMETOOLONG: name too long, open '~/dev/Project0123456789/app_android_xwalk/plug...

### ISSUE THREAD

**Issue by giorgiobeggiora** [facebook-atom/atom-ide-ui#138]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.7.0

### Stack Trace

Uncaught Error: ENAMETOOLONG: name too long, open '/Users/gbeggiora/dev/Unieuro_mobileapp/app_android_xwalk/plugins/cordova-plugin-adyen-checkout/example/plugins/cordova-plugin-adyen-checkout/example/plugins/cordova-plugin-adyen-checkout/example/plugins/cordova-plugin-adyen-checkout/example/plugins/cordova-plugin-adyen-checkout/example/plugins/cordova-plugin-adyen-checkout/example/plugins/cordova-plugin-adyen-checkout/example/plugins/cordova-plugin-adyen-checkout/example/plugins/cordova-plugin-adyen-checkout/example/plugins/cordova-plugin-adyen-checkout/example/plugins/cordova-plugin-adyen-checkout/example/plugins/cordova-plugin-adyen-checkout/example/plugins/cordova-plugin-adyen-checkout/example/plugins/cordova-plugin-adyen-checkout/example/plugins/cordova-plugin-adyen-checkout/example/plugins/cordova-plugin-adyen-checkout/example/plugins/cordova-plugin-adyen-checkout/example/plugins/cordova-plugin-adyen-checkout/example/plugins/cordova-plugin-adyen-checkout/example/plugins/cordova-plugin-adyen-checkout/example/plugins/cordova-plugin-add-swift-support/package.json'

```
At /Users/gbeggiora/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:69

Error: ENAMETOOLONG: name too long, open '/Users/gbeggiora/dev/Unieuro_mobileapp/app_android_xwalk/plugins/cordova-plugin-adyen-checkout/example/plugins/cordova-plugin-adyen-checkout/example/plugins/cordova-plugin-adyen-checkout/example/plugins/cordova-plugin-adyen-checkout/example/plugins/cordova-plugin-adyen-checkout/example/plugins/cordova-plugin-adyen-checkout/example/plugins/cordova-plugin-adyen-checkout/example/plugins/cordova-plugin-adyen-checkout/example/plugins/cordova-plugin-adyen-checkout/example/plugins/cordova-plugin-adyen-checkout/example/plugins/cordova-plugin-adyen-checkout/example/plugins/cordova-plugin-adyen-checkout/example/plugins/cordova-plugin-adyen-checkout/example/plugins/cordova-plugin-adyen-checkout/example/plugins/cordova-plugin-adyen-checkout/example/plugins/cordova-plugin-adyen-checkout/example/plugins/cordova-plugin-adyen-checkout/example/plugins/cordova-plugin-adyen-checkout/example/plugins/cordova-plugin-adyen-checkout/example/plugins/cordova-plugin-adyen-checkout/example/plugins/cordova-plugin-add-swift-support/package.json'
    at /packages/ide-php/node_modules/vscode-jsonrpc/lib/messages.js:46:28)
    at handleResponse (/packages/ide-php/node_modules/vscode-jsonrpc/lib/main.js:430:48)
    at processMessageQueue (/packages/ide-php/node_modules/vscode-jsonrpc/lib/main.js:258:17)
    at /packages/ide-php/node_modules/vscode-jsonrpc/lib/main.js:242:13)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

### Commands

```
     -1:55.2.0 core:select-left (input.hidden-input)
     -1:52.9.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
api-docs 0.0.6 
atom-easy-jsdoc 4.12.4 
atom-ide-ui 0.7.0 
atom-typescript 11.0.10 
autoclose-html 0.23.0 
autocomplete-modules 1.8.0 
autocomplete-paths 2.12.1 
busy-signal 1.4.3 
color-picker 2.2.5 
docblockr 0.13.4 
double-tag 1.1.0 
expand-region 0.4.0 
file-icons 2.1.15 
foldername-tabs 0.2.4 
git-time-machine 1.5.9 
goto-definition 1.3.4 
highlight-selected 0.13.1 
ide-php 0.7.4 
ide-typescript 0.7.2 
intentions 1.1.5 
jsdoc-preview 1.2.1 
language-pug 0.0.21 
linter 2.2.0 
linter-ui-default 1.6.10 
minimap 4.29.7 
minimap-highlight-selected 4.6.1 
multi-cursor-plus 1.2.0 
one-theme-color-by-project 2.0.0 
open-terminal-here 2.3.1 
pigments 0.40.2 
platformio-ide-terminal 2.7.0 
project-manager 3.3.5 
simple-align 0.2.0 
simple-drag-drop-text 0.3.6 
switch-quotes 0.1.0 
vertical-tabs 1.0.5 
webbox-color 0.5.9 
```

**Comment by hansonw** [comment]
The stack trace originates from ide-php - please report this over at https://github.com/atom/ide-php/issues
