### ISSUE TITLE
Uncaught Error: Expected source file F:/work\static\project\zt\2017\1220sljsq\js\share\page.es6 t...

### ISSUE THREAD

**Issue by Lwenli1224** [facebook-atom/atom-ide-ui#140]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.7.0

### Stack Trace

Uncaught Error: Expected source file F:\work\static\project\zt\2017\1220sljsq\js\share\page.es6 to exist in configuration

```
At C:\Users\liwenli.KOOLEARN-INC\.atom\packages\atom-ide-ui\node_modules\rxjs\bundles\Rx.min.js:69

Error: Expected source file F:\work\static\project\zt\2017\1220sljsq\js\share\page.es6 to exist in configuration
    at /packages/ide-css/node_modules/vscode-jsonrpc/lib/messages.js:46:28)
    at handleResponse (/packages/ide-css/node_modules/vscode-jsonrpc/lib/main.js:430:48)
    at processMessageQueue (/packages/ide-css/node_modules/vscode-jsonrpc/lib/main.js:258:17)
    at /packages/ide-css/node_modules/vscode-jsonrpc/lib/main.js:242:13)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

### Commands

```
     -1:13.1.0 core:backspace (input.hidden-input)
     -1:10.3.0 core:move-right (input.hidden-input)
     -1:09.4.0 core:save (input.hidden-input)
     -0:07.2.0 core:backspace (input.hidden-input)
     -0:05.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-ide-ui 0.7.0 
atom-live-server 2.2.0 
atom-ternjs 0.18.3 
chester-atom-syntax 0.3.0 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.15 
ide-css 0.2.0 
ide-json 0.1.0 
ide-typescript 0.7.2 
ide-vue 0.1.8 
intellij-idea-keymap 0.2.3 
javascript-snippets 1.2.1 
js-hyperclick 1.12.2 
language-vue 0.23.1 
language-vue-component 0.5.0 
minimap 4.29.7 
platformio-ide-terminal 2.7.0 
sass 0.5.0 
script 3.17.3 
scss-snippets 0.6.0 
terminal-plus 0.14.5 
tool-bar 1.1.0 
tool-bar-main 0.0.10 
vue2-autocomplete 0.1.0-alpha.4 
vuejs2-snippets 0.15.0 
```

**Comment by Arcanemagus** [comment]
This isn't actually an issue with `atom-ide-ui`, Atom is just reusing the `rxjs` module from its directory and thus it thinks that's where this came from. Unfortunately from your stack trace it doesn't seem obvious which of your packages _actually_ triggered this error, I would look towards the `ide-*` packages though,
 with my guess being `ide-vue` as the culprit.

**Comment by robertrossmann** [comment]
This comes from [ide-typescript (issue)](https://github.com/atom/ide-typescript/issues/72).
