### ISSUE TITLE
Uncaught TypeError: functions.getTokenInfoFunction is not a function

### ISSUE THREAD

**Issue by smith-chris** [facebook-atom/atom-ide-ui#141]
[Enter steps to reproduce:]

1. In linter-elm-make plugin select 'Use Datatips' option
2. Hover over red/green text in error dialog in elm code
<img width="337" alt="screen shot 2017-12-22 at 14 13 32" src="https://user-images.githubusercontent.com/17379615/34300945-5ebcb30c-e722-11e7-8ca7-cb6b56e305f6.png">

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.11.6
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.7.0

### Stack Trace

Uncaught TypeError: functions.getTokenInfoFunction is not a function

```
At /Users/krzysiek/.atom/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:36

TypeError: functions.getTokenInfoFunction is not a function
    at Object.getTokenInfoFunction (/packages/linter-elm-make/lib/parsing.js:1049:17)
    at /packages/linter-elm-make/lib/formatting.js:376:15
    at Object.cb (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:36:125)
    at Object.invokeGuardedCallback (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:35:21)
    at Object.invokeGuardedCallbackAndCatchFirstError (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:35:133)
    at gb (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:36:400)
    at Object.executeDispatchesInOrder (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:38:154)
    at Fb (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:46:103)
    at Hb (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:46:230)
    at Array.forEach (native)
    at Db (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:46:39)
    at Object.processEventQueue (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:49:254)
    at /packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:57:97)
    at xb (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:43:390)
    at batchedUpdates (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:190:243)
    at qb (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:41:344)
    at ob (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:41:278)
    at Object.batchedUpdates (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:42:85)
    at dispatchEvent (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:45:162)
```

### Commands

```
     -2:25.5.0 core:save (input.hidden-input)
  2x -2:25.4.0 linter:toggle (atom-text-editor.editor.is-focused)
     -2:21 datatip:toggle (input.hidden-input)
     -2:21 pane:show-next-item (input.hidden-input)
     -2:17.7.0 pane:show-previous-item (input#linter-elm-make.useDatatips.input-checkbox)
     -2:17.6.0 datatip:toggle (input.hidden-input)
     -2:17.2.0 core:save (input.hidden-input)
  2x -2:17.1.0 linter:toggle (atom-text-editor.editor.is-focused)
     -2:06.1.0 core:save (input.hidden-input)
  2x -2:06.0 linter:toggle (atom-text-editor.editor.is-focused)
     -2:02.1.0 core:save (input.hidden-input)
  2x -2:02.0 linter:toggle (atom-text-editor.editor.is-focused)
     -1:55.9.0 pane:show-previous-item (input#linter-elm-make.useDatatips.input-checkbox)
     -1:55.8.0 datatip:toggle (input.hidden-input)
  4x -0:45 core:backspace (input.hidden-input)
     -0:44.4.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.7 
atom-ide-ui 0.7.0 
atom-react-autocomplete 0.1.10 
autoclose-html 0.23.0 
busy-signal 1.4.3 
elm-format 3.0.0 
expand-region 0.4.0 
file-icons 2.1.15 
highlight-selected 0.13.1 
intentions 1.1.5 
js-refactor 0.7.5 
language-elm 1.5.0 
linter-elm-make 0.28.1 
pigments 0.40.2 
platformio-ide-terminal 2.7.0 
refactor 0.11.5 
restart-atom 0.2.0 
spacegray-atom-dark-syntax 1.3.2 
svg-preview 0.12.1 
zentabs 0.8.9 
```

**Comment by damieng** [comment]
The stack trace indicates this is actually a problem with the linter-elm-make package not atom-ide-ui.

You might want to file it over there at https://github.com/mybuddymichael/linter-elm-make/
