### ISSUE TITLE
Failed to load the atom-ide-ui package

### ISSUE THREAD

**Issue by squibbleFish** [facebook-atom/atom-ide-ui#151]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.2
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.7.2

### Stack Trace

Failed to load the atom-ide-ui package

```
At Cannot find module './modules/nuclide-node-transpiler/lib/env'

Error: Cannot find module './modules/nuclide-node-transpiler/lib/env'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-ide-ui/index-entry.js:34:21)
    at /packages/atom-ide-ui/index-entry.js:42:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:937:35)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:160:34
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:145:18)
    at PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:618:16)
    at config.transact (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:531:20)
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app/src/config.js:342:22)
    at PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:529:23)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:832:34
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-ui 0.7.2 
ide-haskell 2.2.2 
ide-html 0.4.1 
ide-json 0.2.0 
ide-php 0.7.4 
ide-python 0.5.0 
markdown-writer 2.7.3 
pp-markdown 0.0.2 
```

**Comment by hansonw** [comment]
Sounds like some kind of installation error, as that file definitely exists in the release. Follow the steps in https://github.com/facebook-atom/atom-ide-ui/issues/64 to clear APM's cache and reinstall
