### ISSUE TITLE
Failed to load the atom-ide-ui package

### ISSUE THREAD

**Issue by dustinleblanc** [facebook-atom/atom-ide-ui#154]
[Enter steps to reproduce:]

1. Update atom-ide-ui package
2. See error

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.2
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.7.2

### Stack Trace

Failed to load the atom-ide-ui package

```
At Cannot find module './modules/nuclide-node-transpiler/lib/env'

Error: Cannot find module './modules/nuclide-node-transpiler/lib/env'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-ide-ui/index-entry.js:34:21)
    at /packages/atom-ide-ui/index-entry.js:42:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:937:35)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:160:34
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:145:18)
    at PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:618:16)
    at config.transact (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:531:20)
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app/src/config.js:342:22)
    at PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:529:23)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:832:34
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-ui 0.7.2 
atom-jade 0.3.0 
atom-live-server 2.2.0 
autocomplete-js-import 1.4.0 
blade-snippets 0.2.0 
docblock-format-helper 0.3.0 
docblockr 0.13.6 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.16 
ide-go 0.5.0 
ide-php 0.7.4 
ide-ruby 0.1.7 
ide-typescript 0.7.2 
ide-vue 0.1.8 
ide-yaml 0.4.2 
language-blade 0.38.0 
language-docker 1.1.8 
language-systemd 0.1.1 
markdown-pdf 2.1.0 
markdown-themeable-pdf 1.2.0 
markdown-writer 2.7.3 
vim-mode-plus 1.26.0 
```

**Comment by hansonw** [comment]
Looks like an installation issue - please see https://github.com/facebook-atom/atom-ide-ui/issues/64 if reloading didn't fix it
