### ISSUE TITLE
Uncaught Error: Invariant violation: "this._disposables != null"

### ISSUE THREAD

**Issue by fenric** [facebook-atom/atom-ide-ui#169]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Unknown Windows version
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.9.1

### Stack Trace

Uncaught Error: Invariant violation: "this._disposables != null"

```
At C:\Users\a.fenric\.atom\packages\atom-ide-ui\node_modules\react-dom\cjs\react-dom.production.min.js:168

Error: Invariant violation: "this._disposables != null"
    at DiagnosticsTable.componentWillUnmount (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-diagnostics-ui/lib/ui/DiagnosticsTable.js:132:13)
    at /packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:143:273)
    at /packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:143:411)
    at /packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:144:465)
    at commitDeletion (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:148:97)
    at /packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:158:23)
    at /packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:169:217)
    at /packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:168:413)
    at /packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:167:32)
    at /packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:165:441)
    at Object.updateContainer (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:175:31)
    at Pg (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:225:81)
    at /packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:228:69
    at Object.unbatchedUpdates (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:171:453)
    at Object.unmountComponentAtNode (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:228:41)
    at HTMLElement.detachedCallback (/packages/atom-ide-ui/modules/nuclide-commons-ui/ReactMountRootElement.js:35:23)
    at HTMLElement.PaneElement.itemRemoved (/app.asar/src/pane-element.js:199:29)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Pane.removeItem (~/AppData/Local/atom/app-1.24.0/resources/app/src/pane.js:698:24)
    at Pane.moveItemToPane (~/AppData/Local/atom/app-1.24.0/resources/app/src/pane.js:730:16)
    at Object.end (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/tabs/lib/layout.js:63:22)
    at HTMLLIElement.TabView.element.ondragend (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/tabs/lib/tab-view.js:61:29)
```

### Commands

```
     -6:00.7.0 core:backspace (input.hidden-input)
     -5:59.6.0 core:paste (input.hidden-input)
     -5:59 core:confirm (input.hidden-input)
     -5:54.3.0 editor:newline (input.hidden-input)
  3x -5:53 core:backspace (input.hidden-input)
  3x -5:40.6.0 spell-check:correct-misspelling (input.hidden-input)
     -5:03.2.0 core:cut (input.hidden-input)
     -2:53.6.0 spell-check:correct-misspelling (input.hidden-input)
  2x -2:43.5.0 editor:newline (input.hidden-input)
  6x -2:41.9.0 core:backspace (input.hidden-input)
     -2:40.5.0 editor:delete-to-beginning-of-word (input.hidden-input)
     -2:36.7.0 core:backspace (input.hidden-input)
     -2:35.6.0 core:save (input.hidden-input)
  3x -2:23.6.0 core:backspace (input.hidden-input)
     -0:53.3.0 window:toggle-menu-bar (input.hidden-input)
     -0:39.7.0 console:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.9.1 
ide-json 0.2.1 
ide-php 0.7.6 
teletype 0.8.0 
```

**Comment by michael-gracy** [comment]
I can am getting this issue also.

**Comment by matthewwithanm** [comment]
sorry! fix in the next release!

**Comment by hansonw** [comment]
v0.9.2 has this fix
