### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by isu17** [facebook-atom/atom-ide-ui#171]
[Enter steps to reproduce:]

1. Just start it up on fresh update (the latest)
2. ...???

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.13.3
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.9.1

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Users/isu/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:71

TypeError: Cannot read property 'length' of undefined
    at ScreenLineBuilder.emitText (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/screen-line-builder.js:329:30)
    at ScreenLineBuilder.buildScreenLines (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/screen-line-builder.js:141:22)
    at DisplayLayer.getScreenLines (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:643:41)
    at TextEditorComponent.queryScreenLinesToRender (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:867:57)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:376:16)
    at TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:274:16)
    at TextEditorComponent.pixelPositionForScreenPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:206:18)
    at getBufferPosition (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-datatip/lib/DatatipManager.js:192:48)
    at DatatipManagerForEditor._hideOrCancel (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-datatip/lib/DatatipManager.js:554:37)
    at /packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-datatip/lib/DatatipManager.js:330:12)
    at a.__tryOrUnsub (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:71:208)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:70:63)
    at a._next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:68:217)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at /packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:111:270)
```

### Commands

```
```

### Non-Core Packages

```
arduino-toolbelt 0.1.1 
arduino-upload 1.3.2 
atom-beautify 0.30.9 
atom-bracket-highlight 0.3.2 
atom-clang-expand 0.1.3 
atom-clock 0.1.16 
atom-csv-markdown 1.0.2 
atom-django 0.3.2 
atom-ide-ui 0.9.1 
autocomplete-bash-builtins 0.3.5 
autocomplete-javascript 0.0.2 
autocomplete-python 1.10.5 
autocomplete-webpack 0.9.0 
bracket-matcher-highlight 0.5.0 
busy-signal 1.4.3 
chester-atom-syntax 0.3.0 
chestnut-light-atom-syntax 0.2.1 
color-picker 2.2.5 
cpp-generator 1.0.1 
django-templates 0.5.0 
dracula-syntax 2.0.6 
emmet 2.4.3 
es6-javascript 1.0.0 
file-icons 2.1.16 
gcc-make-run 0.2.12 
gist-it 0.9.2 
gitignore-snippets 0.2.5 
gpp-compiler 3.0.7 
highlight-selected 0.13.1 
ide-c 0.0.2 
ide-clangd 0.1.2 
ide-cpp 0.0.3 
ide-css 0.2.0 
ide-flowtype 0.19.0 
ide-html 0.4.1 
ide-json 0.2.1 
ide-python 0.8.0 
ide-rust 0.12.1 
ide-typescript 0.7.3 
ide-vue 0.1.8 
ide-yaml 0.4.2 
intentions 1.1.5 
javascript-snippets 1.2.1 
language-arduino 0.4.3 
language-csv 1.1.2 
language-django 0.1.1 
language-gitignore 0.3.0 
language-rust 0.4.12 
language-vue 0.23.1 
language-vue-component 0.5.0 
linter 2.2.0 
linter-jshint 3.1.6 
linter-rust 0.8.4 
linter-ui-default 1.6.10 
markdown-preview-plus 2.5.3 
monokai 0.24.0 
my-github-profile 0.2.1 
nodejs-snippets 2.0.2 
pristine-ui 1.1.11 
python-debugger 0.2.0 
python-tools 0.6.9 
quick-highlight 0.12.0 
styri-syntax 0.2.0 
tablr 1.8.3 
teletype 0.8.0 
toggler 0.3.1 
tree-view-git-status 1.4.0 
vue-autocomplete 0.1.1 
vue-format 0.4.0 
vue2-autocomplete 0.1.0-alpha.4 
vuejs2-snippets 0.15.0 
```

[-1519303778640.log](https://github.com/facebook-atom/atom-ide-ui/files/1747897/-1519303778640.log)

**Comment by isu17** [comment]
I really cant reproduce it, dont know where the problem is.
And after uninstalling and installing it back again (the Atom itself, could't get pass this error to remove any plugins) it fixed itself.

**Comment by hansonw** [comment]
This seems like an odd race condition in the Atom text editor itself. If it happens again you might want to report it over in the Atom repository instead, since in the `atom-ide-ui` side we're just calling into a `TextEditor` API.
