### ISSUE TITLE
Uncaught Error: Cannot find module './OutlineViewPanel'

### ISSUE THREAD

**Issue by timas130** [facebook-atom/atom-ide-ui#173]
**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Windows 10
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.9.1

### Stack Trace

Uncaught Error: Cannot find module './OutlineViewPanel'

```
At C:\Users\BUser\AppData\Local\atom\app-1.24.0\resources\app\static\<embedded>:1

Error: Cannot find module './OutlineViewPanel'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.24.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.24.0/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.24.0/resources/app/src/native-compile-cache.js:66:33)
    at _load_OutlineViewPanel (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-outline-view/lib/main.js:48:30)
    at HTMLElement.atom.commands.add (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-outline-view/lib/main.js:99:51)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.24.0/resources/app/src/command-registry.js:388:36)
    at Object.didConfirmSelection (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/command-palette/lib/command-palette-view.js:165:35)
    at SelectListView.confirmSelection (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:401:26)
    at HTMLDivElement.core:confirm (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:106:20)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.24.0/resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.24.0/resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -0:15.3.0 command-palette:toggle (input.hidden-input)
     -0:10.8.0 core:confirm (input.hidden-input)
     -0:10.8.0 outline-view:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-ide-ui 0.9.1 
autocomplete-boilerplate 0.2.0 
autocomplete-html-entities 0.2.0 
highlight-selected 0.13.1 
Hydrogen 2.2.3 
ide-html 0.4.1 
language-ini 1.19.0 
language-vue 0.23.1 
minimap 4.29.8 
node-debugger undefined 
platformio-ide-terminal 2.8.0 
teletype 0.8.0 
vue-format 0.4.0 
vue2-autocomplete 0.1.0-alpha.4 
```

**Comment by hansonw** [comment]
This is typically an error caused by an installation bug. Try some of the steps at https://github.com/facebook-atom/atom-ide-ui/issues/64.
