### ISSUE TITLE
seeing this repeatedly after latest update

### ISSUE THREAD

**Issue by rcrooks** [facebook-atom/atom-ide-ui#184]
doesn't seem specific to any language

happening every time I save a doc
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0-beta2 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.4
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.9.2

### Stack Trace

Uncaught TypeError: (0 , (_textEditor || _load_textEditor(...)).getNonWordCharacters) is not a function

```
At /Users/rcrooks/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:70

TypeError: (0 , (_textEditor || _load_textEditor(...)).getNonWordCharacters) is not a function
    at wordAtPosition (/packages/atom-ide-ui/modules/nuclide-commons-atom/range.js:38:87)
    at /packages/atom-ide-ui/modules/atom-ide-ui/pkg/hyperclick/lib/HyperclickForTextEditor.js:287:68)
    at a.__tryOrSetError (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:71:319)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:70:6)
    at a._next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:68:217)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a._next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:184:201)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a._next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:194:28)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a._next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:183:159)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a._next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:136:208)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:77:124)
    at HyperclickForTextEditor._fetchSuggestion (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/hyperclick/lib/HyperclickForTextEditor.js:247:23)
    at HyperclickForTextEditor._onKeyDown (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/hyperclick/lib/HyperclickForTextEditor.js:227:12)
```

### Commands

```
     -1:51.4.0 core:close (input.hidden-input)
     -0:10.6.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-ayu-mirage-atom-syntax.theme-minima-ui.teletype-Authenticated)
```

### Non-Core Packages

```
aligner 1.2.4 
aligner-css 1.2.1 
aligner-javascript 1.3.0 
aligner-php 1.2.0 
api-workbench 0.8.47 
apidoc-snippets 0.1.1 
atom-beautify 0.32.0 
atom-html-preview 0.2.5 
atom-ide-ui 0.9.2 
atom-json 0.6.0 
atom-json-color 0.6.0 
atom-json-editor 0.4.1 
atom-minify 0.8.0 
atom-package-sync 0.2.6 
autoclose-html 0.23.0 
autocomplete-html-entities 0.2.0 
autocomplete-json 5.5.2 
autoupdate-packages 1.3.1 
ayu-mirage-atom-syntax 1.0.0 
birds-syntax 0.2.1 
block-select 1.0.0 
busy-signal 1.4.3 
city-lights-syntax 1.1.8 
city-lights-ui 1.3.3 
Delete-Whitelines 0.6.3 
directory-color 0.3.0 
docblockr 0.13.7 
double-tag 1.1.0 
emmet 2.4.3 
fancy-bracket-matcher 2.1.0 
file-icons 2.1.17 
gaia-dark-syntax 2.1.0 
html-to-less 1.2.2 
html-wrapper 0.2.0 
iceberg-syntax 0.2.3 
ide-css 0.2.0 
ide-css-less-scss 0.1.1 
ide-html 0.4.2 
ide-json 0.2.1 
ide-php 0.7.8 
ide-yaml 0.4.2 
indent-guide-improved 1.4.13 
intentions 1.1.5 
javascript-snippets 1.2.1 
json-schema 0.1.15 
language-vtt 0.0.2 
line-number-color 0.2.0 
linter 2.2.0 
linter-htmllint 1.0.1 
linter-js-yaml 1.2.8 
linter-jshint 3.1.6 
linter-raml 1.0.1 
linter-ui-default 1.7.1 
minima-syntax 0.0.2 
minima-ui 0.0.3 
multi-cursor 2.1.5 
NatureBoi 2.0.0 
noir-dark-syntax 0.1.0 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
one-liner 0.1.3 
pigments 0.40.2 
platformio-ide-terminal 2.8.0 
playa-dark-syntax 2.1.0 
predawn-syntax 1.0.4 
pristine-ui 1.1.11 
quilt-syntax 0.4.0 
rain-syntax 2.1.2 
raml 0.2.0 
raml-snippets 0.1.0 
red-wavy-underline 0.3.3 
simple-drag-drop-text 0.4.0 
splash-ui 0.4.0 
tag 0.5.0 
talamasca 1.3.0 
teletype 0.9.0 
todo-show 2.2.0 
toggle-quotes 1.1.0 
tree-view-git-branch 0.1.2 
tree-view-git-status 1.4.0 
tuesday-syntax 0.1.2 
w3c-validation 0.4.0 
```

**Comment by hansonw** [comment]
Did you restart Atom after the update? Otherwise try clearing Atom's compile cache and re-installing: https://github.com/facebook-atom/atom-ide-ui/issues/64
