### ISSUE TITLE
Failed to activate the atom-ide-ui package

### ISSUE THREAD

**Issue by emayljames** [facebook-atom/atom-ide-ui#186]
I updated to atom-ide-ui 0.9.4 and have permissions for the locations described in the error.

### Description
Error loading Less stylesheet: /home/user/.atom/packages/atom-ide-ui/modules/nuclide-commons-ui/styles/ResizeSensitiveContainer.less
EACCES: permission denied, open '/home/user/.atom/compile-cache/less/e922ae18a706a5fb8d2dfdd35737c0cb141c83e7/content/4b79d1c58a32070af2c703295f12988db3ae1ee6/ResizeSensitiveContainer.json'
(ALSO:)
Failed to activate the atom-ide-ui package
EACCES: permission denied, open '/home/user/.atom/compile-cache/less/e922ae18a706a5fb8d2dfdd35737c0cb141c83e7/content/4b79d1c58a32070af2c703295f12988db3ae1ee6/ResizeSensitiveContainer.json'

### Expected Behavior
atom-ide-ui package should activate on startup.

### Actual Behavior
Failed to activate the atom-ide-ui package.

### Versions
* Atom: 1.25.0-beta3
* Client OS: Ubuntu 17.10 Artful x64
* atom-ide-ui:

### Additional Details
* Installed packages:
About
Archive View
Atom Beautify
Atom Dark Syntax
Atom Dark Ui
Atom Ide Ui
Atom Light Syntax
Atom Light Ui
Autocomplete Atom Api
Autocomplete Css
Autocomplete Html
Autocomplete Plus
Autocomplete Snippets
Autoflow
Autosave
Background Tips
Base16 Tomorrow Dark Theme
Base16 Tomorrow Light Theme
Bookmarks
Bracket Matcher
Chameleon Ui
Command Palette
Dalek
Deprecation Cop
Dev Live Reload
Encoding Selector
Exception Reporting
File Icons
Find And Replace
Fuzzy Finder
Git Diff
Github
Go To Line
Grammar Selector
Ide Css
Ide Html
Ide Json
Ide Php
Ide Standardjs
Image View
Imagemin
Incompatible Packages
Keybinding Resolver
Language C
Language Clojure
Language Coffee Script
Language Csharp
Language Css
Language Gfm
Language Git
Language Go
Language Html
Language Hyperlink
Language Java
Language Javascript
Language Json
Language Less
Language Make
Language Mustache
Language Objective C
Language Perl
Language Php
Language Property List
Language Python
Language Ruby
Language Ruby On Rails
Language Sass
Language Shellscript
Language Source
Language Sql
Language Text
Language Todo
Language Toml
Language Typescript
Language Xml
Language Yaml
Line Ending Selector
Link
Markdown Preview
Metrics
Notifications
Numix Ui
One Dark Syntax
One Dark Ui
One Light Syntax
One Light Ui
Open On Github
Package Generator
Package List
Settings View
Snippets
Solarized Dark Syntax
Solarized Light Syntax
Spell Check
Status Bar
Styleguide
Styri Syntax
Svgo
Symbols View
Tabs
Timecop
Tree View
Update Package Dependencies
Welcome
Whitespace
Wrap Guide
Xatom Ui

###Stack Trace
Error: EACCES: permission denied, open '/home/user/.atom/compile-cache/less/e922ae18a706a5fb8d2dfdd35737c0cb141c83e7/content/4b79d1c58a32070af2c703295f12988db3ae1ee6/ResizeSensitiveContainer.json'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1326:33)
    at Proxy.writeFileSync (/usr/share/atom-beta/resources/app/node_modules/fs-plus/lib/fs-plus.js:298:29)
    at LessCache.module.exports.LessCache.writeJson (/usr/share/atom-beta/resources/app/node_modules/less-cache/lib/less-cache.js:212:23)
    at LessCache.module.exports.LessCache.putCachedCss (/usr/share/atom-beta/resources/app/node_modules/less-cache/lib/less-cache.js:300:18)
    at LessCache.module.exports.LessCache.cssForFile (/usr/share/atom-beta/resources/app/node_modules/less-cache/lib/less-cache.js:358:18)
    at LessCache.module.exports.LessCache.readFileSync (/usr/share/atom-beta/resources/app/node_modules/less-cache/lib/less-cache.js:342:27)
    at LessCompileCache.module.exports.LessCompileCache.read (/usr/share/atom-beta/resources/app/src/less-compile-cache.js:39:31)
    at ThemeManager.loadLessStylesheet (/usr/share/atom-beta/resources/app/src/theme-manager.js:284:37)
    at ThemeManager.loadStylesheet (/usr/share/atom-beta/resources/app/src/theme-manager.js:248:25)
    at ThemeManager.requireStylesheet (/usr/share/atom-beta/resources/app/src/theme-manager.js:175:34)
    at styleDisposables.default._fs.default.readdirSync.filter.map.file (/home/user/.atom/packages/atom-ide-ui/modules/nuclide-commons-ui/index.js:63:225)
    at Array.map (native)
    at Object.<anonymous> (/home/user/.atom/packages/atom-ide-ui/modules/nuclide-commons-ui/index.js:63:201)
    at Object.<anonymous> (/home/user/.atom/packages/atom-ide-ui/modules/nuclide-commons-ui/index.js:66:3)
    at Module.get_Module._compile (/usr/share/atom-beta/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom-beta/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///usr/share/atom-beta/resources/app.asar/static/index.js:47:45)
    at require (/usr/share/atom-beta/resources/app/src/native-compile-cache.js:66:33)
    at Object.activate (/home/user/.atom/packages/atom-ide-ui/index.js:73:85)
    at Package.activateNow (/usr/share/atom-beta/resources/app/src/package.js:230:33)
    at measure (/usr/share/atom-beta/resources/app/src/package.js:206:33)
    at Package.measure (/usr/share/atom-beta/resources/app/src/package.js:88:25)
    at activationPromise.Promise (/usr/share/atom-beta/resources/app/src/package.js:200:20)
    at Promise (<anonymous>)
    at Package.activate (/usr/share/atom-beta/resources/app/src/package.js:198:38)

**Comment by emayljames** [comment]
Just to add: The json file described above is not present ('/home/user/.atom/compile-cache/less/e922ae18a706a5fb8d2dfdd35737c0cb141c83e7/content/4b79d1c58a32070af2c703295f12988db3ae1ee6/ResizeSensitiveContainer.json').

Permissions for the folder are fine.

**Comment by hansonw** [comment]
Hmm, this doesn't seem like an `atom-ide-ui` issue. `~/.atom/compile-cache` can be safely removed so I'd try to `sudo rm -rf ~/.atom/compile-cache`, restart Atom, and see what happens.

**Comment by emayljames** [comment]
Thank you Hansonw, that worked perfectly.

**Comment by rcrooks** [comment]
@emayljames  sadly, that fix did not work for me The error I'm getting is slightly different, though it points to this issue.
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.30.0-beta1 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.6
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.13.0


### Stack Trace

Failed to activate the atom-ide-ui package

```
At variable @font-family is undefined in /Users/rcrooks/.atom/packages/atom-ide-ui/modules/nuclide-commons-ui/styles/TextEditorBanner.less:15:15

LessError: variable @font-family is undefined
at /Users/rcrooks/.atom/packages/atom-ide-ui/modules/nuclide-commons-ui/styles/TextEditorBanner.less:15:15
```

### Commands

```
```

### Non-Core Packages

```
aligner 1.2.4 
aligner-javascript 1.3.0 
atom-beautify 0.33.0 
atom-file-icons 0.6.0 
atom-ide-ui 0.13.0 
atom-patternfly-syntax 1.1.0 
atom-patternfly-ui 3.0.1 
atom-to-codepen 1.0.0 
auto-update-packages 1.0.1 
ayu-mirage-ish-syntax 1.1.0 
balanced-theme 1.0.0 
better-behavior-syntax 0.1.1 
birds-syntax 0.2.1 
busy-signal 1.4.3 
camelcase-to-space 1.0.2 
directory-color 0.3.0 
docblockr 0.13.7 
double-tag 1.5.0 
emmet 2.4.3 
emmet-snippets-compatibility 1.0.6 
fancy-bracket-matcher 2.1.0 
flexible-ui 0.10.7 
highlight-selected 0.14.0 
html-wrapper 0.2.0 
ide-html 0.4.2 
ide-json 0.2.1 
indent-guide-improved 1.4.13 
intentions 1.1.5 
javascript-snippets 1.2.1 
json-level-color 0.1.4 
json-refs 0.1.3 
language-apidoc 0.1.0 
line-number-color 0.2.0 
linen-syntax 0.5.0 
linter 2.2.0 
linter-jsonlint 1.3.0 
linter-ui-default 1.7.1 
markdown-toc 0.4.2 
multi-cursor 2.1.5 
pear-dark-syntax 1.0.9 
pigments 0.40.2 
platformio-ide-terminal 2.8.4 
pubster-syntax 3.0.2 
rain-syntax 2.1.2 
red-wavy-underline 0.3.3 
simple-code-index 1.7.0 
splash-ui 0.4.0 
swackets 0.35.0 
sync-settings 0.8.6 
talamasca 1.3.0 
tuesday-syntax 0.1.2 
vibrance-ui 0.1.2 
```
