### ISSUE TITLE
Uncaught TypeError: (0 , (_ContextMenu || _load_ContextMenu(...)).showMenuForEvent) is not a func...

### ISSUE THREAD

**Issue by aTastyCookie** [facebook-atom/atom-ide-ui#204]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.1 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.4
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.9.4

### Stack Trace

Uncaught TypeError: (0 , (_ContextMenu || _load_ContextMenu(...)).showMenuForEvent) is not a function

```
At /Users/d34dr00t/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:71

TypeError: (0 , (_ContextMenu || _load_ContextMenu(...)).showMenuForEvent) is not a function
    at /packages/nuclide/pkg/nuclide-file-tree/components/FileTreeSidebarComponent.js:378:117)
    at b._trySubscribe (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:73:217)
    at b.subscribe (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:73:43)
    at /packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:33:305)
    at a._innerSub (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:262:1)
    at a._next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:261:375)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at /packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:111:270)
```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.16 
atom-ide-ui 0.9.4 
autoclose-html 0.23.0 
autocomplete-html-entities 0.2.0 
autocomplete-python 1.10.5 
busy-signal 1.4.3 
highlight-selected 0.13.1 
intentions 1.1.5 
language-gitignore 0.3.0 
linter 2.2.0 
linter-ui-default 1.7.1 
markdown-preview-plus 2.5.7 
nuclide 0.293.0 
pretty-json 2.0.0 
python-indent 1.1.5 
remote-edit 1.9.0 
script 3.17.3 
teletype 0.12.0 
xml-formatter 0.11.0 
```

**Comment by hansonw** [comment]
No need to have both `nuclide` and `atom-ide-ui` installed - `nuclide` comes with `atom-ide-ui` bundled with it. Removing one of them and restarting should resolve this issue.
