### ISSUE TITLE
Uncaught TypeError: Cannot read property 'type' of null

### ISSUE THREAD

**Issue by mm-tfx** [facebook-atom/atom-ide-ui#205]
[Enter steps to reproduce:]

1. Open Atom
2. Work with some Elm files.
No specific action that triggers this fault or at least I cannot specify such action.
Perhaps it has something with installing Elm packages with elmjutsu package but I am not sure.

**Atom**: 1.25.1 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.9.4

### Stack Trace

Uncaught TypeError: Cannot read property 'type' of null

```
.atom\packages\atom-ide-ui\node_modules\rxjs\bundles\Rx.min.js:34

TypeError: Cannot read property 'type' of null
    at linterMessagesToDiagnosticUpdate (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-diagnostics/lib/services/LinterAdapter.js:208:34)
    at /packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-diagnostics/lib/services/LinterAdapter.js:276:22)
    at a._next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:261:315)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a.notifyNext (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:88:375)
    at a._next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:90:52)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at /packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:33:484
    at <anonymous>
```

### Commands

```
     -1:17.4.0 elmjutsu:install-package (input.hidden-input)
     -0:47.3.0 editor:select-to-first-character-of-line (input.hidden-input)
     -0:46.8.0 intentions:highlight (input.hidden-input)
     -0:46.4.0 core:copy (input.hidden-input)
     -0:36.7.0 editor:newline (input.hidden-input)
     -0:36.5.0 intentions:highlight (input.hidden-input)
     -0:36.2.0 core:paste (input.hidden-input)
  3x -0:32.5.0 intentions:highlight (input.hidden-input)
     -0:31.9.0 core:save (input.hidden-input)
  2x -0:31.5.0 linter:toggle (atom-text-editor.editor.is-focused)
```

### Non-Core Packages

```
api-workbench 0.8.48 
atom-html-preview 0.2.5 
atom-ide-ui 0.9.4 
autoclose-html 0.23.0 
autocomplete-haskell 1.0.1 
busy-signal 1.4.3 
elm-format 3.0.0 
elmjutsu 7.3.4 
git-plus 7.10.2 
haskell-ghc-mod 2.2.3 
ide-haskell 2.3.1 
ide-haskell-cabal 2.2.0 
ide-haskell-repl 0.8.0 
intentions 1.1.5 
language-elixir 0.22.0 
language-elm 1.5.0 
language-erlang 3.2.0 
language-haskell 1.17.3 
language-plantuml 0.2.0 
linter 2.2.0 
linter-elm-make 0.28.3 
linter-ui-default 1.7.1 
plantuml-viewer 0.7.2 
pretty-json 2.0.0 
```

**Comment by Arcanemagus** [comment]
This is a bug in `linter-elm-make`.

In [this chunk of code](https://github.com/mybuddymichael/linter-elm-make/blob/1c907bf81fa1b51ece9b2795967b4a7ecdee1ea8/lib/linter-elm-make.js#L1167-L1178) they attempt to use `executeElmMake` on multiple paths at the same time, but it was only designed to return results as if it was returning directly to `provideLinter`. As such it _can_ return `null`, which then gets `flatten`ed into the final return Array and attempted to be parsed as a valid message here... which it isn't.

Please file this issue over there to get it fixed, thanks!

**Comment by mm-tfx** [comment]
I have raised an issue there.
