### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received null

### ISSUE THREAD

**Issue by dpriedel** [facebook-atom/atom-ide-ui#216]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.0 x64
**Electron**: 1.8.4
**OS**: "Manjaro Linux"
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.11.0

### Stack Trace

Uncaught TypeError: Path must be a string. Received null

```
At /home/dpriedel/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:93

TypeError: Path must be a string. Received null
    at assertPath (path.js:28:11)
    at Object.relative (path.js:1247:5)
    at server.disposable.add.atom.workspace.onDidChangeActiveTextEditor.editor (/packages/ide-cquery/lib/main.js:114:16)
    at Function.module.exports.Emitter.simpleDispatch (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:141:28)
    at Workspace.didChangeActivePaneItemOnPaneContainer (/usr/lib/atom/src/workspace.js:436:22)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (/usr/lib/atom/src/workspace-center.js:17:14)
    at Function.module.exports.Emitter.simpleDispatch (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:141:28)
    at PaneContainer.didChangeActiveItemOnPane (/usr/lib/atom/src/pane-container.js:281:20)
    at Pane.setActiveItem (/usr/lib/atom/src/pane.js:440:42)
    at Pane.activateItem (/usr/lib/atom/src/pane.js:579:12)
    at Workspace.open (/usr/lib/atom/src/workspace.js:1028:12)
    at <anonymous>
```

### Commands

```
     -1:13.3.0 debugger:show-launch-dialog (input.hidden-input)
     -1:01.8.0 editor:move-to-first-character-of-line (input.hidden-input)
     -0:56 core:confirm (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-atom-dark-ui)
     -0:56 debugger:show (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-atom-dark-ui)
     -0:33.5.0 debugger:show-launch-dialog (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-atom-dark-ui)
     -0:29.8.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:20.5.0 core:confirm (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-atom-dark-ui)
     -0:20.5.0 debugger:show (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-atom-dark-ui)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atom-ctags 5.1.2 
atom-eclipse-syntax 0.0.5 
atom-htmltidy 5.1.0 
atom-ide-debugger-native-gdb 0.7.1 
atom-ide-debugger-python 0.7.1 
atom-ide-ui 0.11.0 
atom-visual-studio-code-light-ui 1.1.11 
atom-visual-studio-code-ui 1.3.4 
autocomplete-python-jedi 1.10.3-0 
build 0.70.0 
build-cmake 0.11.0 
build-tools 4.5.12 
busy-signal 1.4.3 
clipboard-plus 0.5.1 
data-atom 0.29.0 
editorconfig 2.2.2 
ex-mode 0.18.0 
foldername-tabs 0.2.4 
git-control 0.9.0 
git-diff-details 1.4.0 
git-status 0.3.4 
git-time-machine 1.5.9 
gl-light-syntax 3.0.0 
gtk-dark-theme 0.1.4 
highlight-selected 0.13.1 
Hydrogen 2.4.1 
hydrogen-launcher 1.2.2 
hydrogen-python 0.0.6 
ide-cquery 0.10.0 
ide-json 0.2.1 
ide-python 0.9.2 
intentions 1.1.5 
language-antlr4 0.1.0 
language-cmake 1.1.0 
language-cpp14 0.6.2 
language-ipynb 1.3.0 
language-latex 1.1.1 
language-pgsql 0.2.3 
latex 0.50.0 
latex-plus 0.9.1 
linter 2.2.0 
linter-eslint 8.4.1 
linter-flake8 2.3.0 
linter-shellcheck 1.4.7 
linter-ui-default 1.7.1 
MagicPython 1.0.12 
monokai 0.24.0 
pdf-view 0.69.0 
platformio-ide-terminal 2.8.1 
project-manager 3.3.5 
scroll-sync 0.2.4 
seti-ui 1.10.0 
spacegray-light-neue-ui 0.1.7 
split-diff 1.5.2 
structure-view 0.2.1 
symbols-tree-nav 0.15.5 
vim-mode-clipboard-plus 0.2.0 
vim-mode-plus 1.32.0 
vim-mode-plus-keymaps-for-surround 0.2.1 
vim-mode-plus-project-find-from-search 0.2.0 
you-complete-me 0.8.0 
```

**Comment by dpriedel** [comment]
Thanks.  Will do.

Sorry for the noise...
