### ISSUE TITLE
0.11.1 update breaks atom-ide native gdb debugger

### ISSUE THREAD

**Issue by dpriedel** [facebook-atom/atom-ide-ui#219]
Just installed the 0.11.1 update and now I can't run the debugger.

The following messages print in the console window.

2:46:13 PM
TypeError: Buffer is not a constructor
2:46:13 PM
    at MIDebugSession.ProtocolServer.start (/home/dpriedel/.atom/packages/atom-ide-debugger-native-gdb/node_modules/vscode-debugadapter/lib/protocol.js:23:25)
2:46:13 PM
    at MIDebugSession.LoggingDebugSession.start (/home/dpriedel/.atom/packages/atom-ide-debugger-native-gdb/node_modules/vscode-debugadapter/lib/loggingDebugSession.js:22:32)
2:46:13 PM
    at MIDebugSession.start (/home/dpriedel/.atom/packages/atom-ide-debugger-native-gdb/node_modules/atom-ide-debugger-native-gdb/lib/MIDebugSession.js:163:11)
2:46:13 PM
    at Function.DebugSession.run (/home/dpriedel/.atom/packages/atom-ide-debugger-native-gdb/node_modules/vscode-debugadapter/lib/debugSession.js:306:23)
2:46:13 PM
    at Object.<anonymous> (/home/dpriedel/.atom/packages/atom-ide-debugger-native-gdb/node_modules/atom-ide-debugger-native-gdb/lib/MIDebugSession.js:915:73)
2:46:13 PM
    at Object.<anonymous> (/home/dpriedel/.atom/packages/atom-ide-debugger-native-gdb/node_modules/atom-ide-debugger-native-gdb/lib/MIDebugSession.js:916:3)
2:46:13 PM
    at Module._compile (/home/dpriedel/.atom/packages/atom-ide-debugger-native-gdb/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
2:46:13 PM
    at Object.Module._extensions..js (module.js:580:10)
2:46:13 PM
    at Module.load (module.js:503:32)
2:46:13 PM
    at tryModuleLoad (module.js:466:12)

Dave Riedel

**Comment by hansonw** [comment]
Sorry, I think the debugger also needs a bump - I'll see to it

**Comment by hansonw** [comment]
Sorry for the delay. v0.7.2 of https://atom.io/packages/atom-ide-debugger-native-gdb should resolve this!
