### ISSUE TITLE
TypeError: Buffer is not a constructor

### ISSUE THREAD

**Issue by maxbrunsfeld** [facebook-atom/atom-ide-ui#227]
### Description

I'm getting an error in the console when trying to launch a debugger using `atom-ide-debugger-native-gdb`:

```
/Users/max/.atom/packages/atom-ide-debugger-native-gdb/node_modules/vscode-debugadapter/lib/protocol.js:23
        this._rawData = new Buffer(0);
                        ^

TypeError: Buffer is not a constructor
    at MIDebugSession.ProtocolServer.start (/Users/max/.atom/packages/atom-ide-debugger-native-gdb/node_modules/vscode-debugadapter/lib/protocol.js:23:25)
    at MIDebugSession.LoggingDebugSession.start (/Users/max/.atom/packages/atom-ide-debugger-native-gdb/node_modules/vscode-debugadapter/lib/loggingDebugSession.js:22:32)
    at MIDebugSession.start (/Users/max/.atom/packages/atom-ide-debugger-native-gdb/node_modules/atom-ide-debugger-native-gdb/lib/MIDebugSession.js:163:11)
    at Function.DebugSession.run (/Users/max/.atom/packages/atom-ide-debugger-native-gdb/node_modules/vscode-debugadapter/lib/debugSession.js:306:23)
    at Object.<anonymous> (/Users/max/.atom/packages/atom-ide-debugger-native-gdb/node_modules/atom-ide-debugger-native-gdb/lib/MIDebugSession.js:915:73)
    at Object.<anonymous> (/Users/max/.atom/packages/atom-ide-debugger-native-gdb/node_modules/atom-ide-debugger-native-gdb/lib/MIDebugSession.js:916:3)
    at Module._compile (/Users/max/.atom/packages/atom-ide-debugger-native-gdb/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

### Expected Behavior
Tell us what should happen.

### Actual Behavior
Tell us what happens instead.

### Versions
* Atom:
* Client OS:
* atom-ide-ui:

### Additional Details
* Installed packages (`apm ls --installed`):

**Comment by hansonw** [comment]
Sorry Max! I need to publish a new version of `atom-ide-debugger-native-gdb` - hopefully I can get that out today.
Merging into https://github.com/facebook-atom/atom-ide-ui/issues/219

**Comment by maxbrunsfeld** [comment]
Thanks!
