### ISSUE TITLE
Uncaught TypeError: Cannot read property '4' of undefined

### ISSUE THREAD

**Issue by mcelkys** [facebook-atom/atom-ide-ui#233]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.11.1

### Stack Trace

Uncaught TypeError: Cannot read property '4' of undefined

```
At C:\Users\mindaugas.celkys\.atom\packages\atom-ide-ui\node_modules\rxjs\bundles\Rx.min.js:71

TypeError: Cannot read property '4' of undefined
    at TextEditorComponent.renderedScreenLineForRow (~/AppData/Local/atom/app-1.26.1/resources/app/src/text-editor-component.js:977:37)
    at TextEditorComponent.screenPositionForPixelPosition (~/AppData/Local/atom/app-1.26.1/resources/app/src/text-editor-component.js:2396:33)
    at TextEditorComponent.screenPositionForMouseEvent (~/AppData/Local/atom/app-1.26.1/resources/app/src/text-editor-component.js:1971:23)
    at getBufferPosition (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-datatip/lib/DatatipManager.js:155:2849)
    at DatatipManagerForEditor._hideOrCancel (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-datatip/lib/DatatipManager.js:616:37)
    at /packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-datatip/lib/DatatipManager.js:328:12)
    at a.__tryOrUnsub (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:71:208)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:70:63)
    at a._next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:68:217)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at /packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:111:270)
```

### Commands

```
     -1:28.3.0 core:delete (input.hidden-input)
     -1:26 core:undo (input.hidden-input)
     -1:23.1.0 tree-view:remove (li.file.entry.list-item.selected)
```

### Non-Core Packages

```
atom-ide-ui 0.11.1 
atom-ternjs 0.18.3 
ide-java 0.8.3 
ide-typescript 0.7.6 
react 0.18.0 
```

**Comment by hansonw** [comment]
Are you still able to reproduce this? It's probably resolved in a newer combination of Atom/atom-ide-ui versions. (Re-open if not.)
