### ISSUE TITLE
Uncaught Error: Cannot find module 'nuclide-commons-atom/range'

### ISSUE THREAD

**Issue by jayallen** [facebook-atom/atom-ide-ui#235]
I wish I could tell you how to reproduce this or even what the effects of the issue are aside from the [error message](https://www.evernote.com/shard/s4/sh/38ab9e01-8f53-45e4-aae2-9ae706407ed6/4f108eb021e0da40) (included below in entirety w/ stack trace) but it's happened enough times in the last few days that I thought I'd create an issue.  I'll work on figuring out steps to reproduce.

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.12.6
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.11.1

### Stack Trace

Uncaught Error: Cannot find module 'nuclide-commons-atom/range'

```
At /Users/jay/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:70

Error: Cannot find module 'nuclide-commons-atom/range'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at _load_range (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/hyperclick/lib/HyperclickForTextEditor.js:20:41)
    at /packages/atom-ide-ui/modules/atom-ide-ui/pkg/hyperclick/lib/HyperclickForTextEditor.js:292:38)
    at a.__tryOrSetError (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:71:319)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:70:6)
    at a._next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:68:217)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a._next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:184:201)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a._next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:194:28)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a._next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:183:159)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a._next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:136:208)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:77:124)
    at HyperclickForTextEditor._fetchSuggestion (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/hyperclick/lib/HyperclickForTextEditor.js:244:23)
    at HyperclickForTextEditor._onKeyDown (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/hyperclick/lib/HyperclickForTextEditor.js:224:12)
```

### Commands

```
     -4:06.9.0 datatip:toggle (input.hidden-input)
     -4:06.8.0 intentions:highlight (input.hidden-input)
     -4:06.8.0 datatip:toggle (input.hidden-input)
  5x -4:05.5.0 core:move-down (input.hidden-input)
  2x -4:03.7.0 core:move-up (input.hidden-input)
     -4:03.1.0 core:move-down (input.hidden-input)
     -4:02.8.0 intentions:highlight (input.hidden-input)
     -4:02.7.0 editor:move-to-beginning-of-word (input.hidden-input)
     -4:02.4.0 datatip:toggle (input.hidden-input)
     -3:55.8.0 core:backspace (input.hidden-input)
     -3:54.7.0 intentions:highlight (input.hidden-input)
     -3:54.6.0 editor:move-to-end-of-word (input.hidden-input)
     -3:54.3.0 datatip:toggle (input.hidden-input)
  3x -3:21.4.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -3:16.1.0 settings-view:open (input.hidden-input)
  2x -3:08.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-easy-jsdoc 4.12.5 
atom-ide-ui 0.11.1 
atom-lorempixel 0.1.0 
atom-nodejs-snippets 2.1.1 
atom-typescript 12.4.1 
busy-signal 1.4.3 
duplicate-removal 0.1.3 
es6-javascript 1.0.0 
ide-css 0.3.0 
ide-json 0.2.1 
ide-php 0.7.14 
ide-python 0.9.2 
ide-standardjs 0.0.1 
ide-typescript 0.7.6 
ide-yaml 0.4.3 
intentions 1.1.5 
language-babel 2.85.0 
language-javascript-jsx 0.3.7 
linter 2.2.0 
linter-eslint 8.4.1 
linter-js-standard 5.0.0 
linter-perl 0.8.2 
linter-perlcritic 2.1.0 
linter-stylelint 4.3.0 
linter-ui-default 1.7.1 
lorem 1.5.0 
lorem-ricksum 0.2.1 
node-debugger 1.10.1 
perltidy 4.0.0 
pipe 0.4.0 
prettier-atom 0.53.0 
project-manager 3.3.5 
react-es6-snippets 0.3.0 
react-snippets 1.1.0 
sort-lines 0.18.0 
toggle-quotes 1.1.0 
```

**Comment by jayallen** [comment]
It seems to happen reliably when I open a file from the tree view sidebar, click into the document (the error is sometimes thrown here) and do **Command-[any arrow key]**.  If it's not triggered when clicking into the document pane, it's definitely triggered with the keyboard combo.

**Comment by jayallen** [comment]
A few notes:

* The module it can't find does seem to be there:

```
 $ find /Users/jay/.atom/packages  -path '*/nuclide-commons-atom/range.js'  -ls
57324370       24 -rw-r--r--    1 jay              staff                9508 Apr 27 02:16 /Users/jay/.atom/packages/atom-ide-ui/modules/nuclide-commons-atom/range.js
 $ md5 /Users/jay/.atom/packages/atom-ide-ui/modules/nuclide-commons-atom/range.js
MD5 (/Users/jay/.atom/packages/atom-ide-ui/modules/nuclide-commons-atom/range.js) = 6690611c2bec08eab5b86a31f5aff0e3
```
* [The latest release](https://github.com/facebook-atom/atom-ide-ui/releases) of atom-ide-ui is reported to be **v0.11.0** and yet I somehow have **v0.11.1** (which btw is also listed there, just not marked as the latest release).
* Although this may have no bearing whatsoever, I notice that the [diff between v0.11.0 and v0.11.1 is *huge*](https://github.com/facebook-atom/atom-ide-ui/commit/1cb31c3c067be66d38e91f98c71f4339c273e644) and [that module is no exception](https://github.com/facebook-atom/atom-ide-ui/commit/1cb31c3c067be66d38e91f98c71f4339c273e644#diff-778957e02dcda427d92f8a1fbd091d30L1). Webpack maybe?
* Taking notice those weird changes to range.js, I noticed that `atom-ide-ui/modules/nuclide-commons-atom/package.json` is reporting **v0.7.0-dev** but [the module in the nuclide repo](https://github.com/facebook/nuclide/blob/9b8bd6f079aaee9a75e1c02651412bcce4e45d9a/modules/nuclide-commons-atom/range.js) was bumped to **v0.7.1-dev** on April 23rd and definitely doesn't have those same changes.  Again, I have no idea is that's significant.  It's just something I notices.

**Comment by hansonw** [comment]
Can you try the steps in https://github.com/facebook-atom/atom-ide-ui/issues/64?
Also see if you have a `~/node_modules/nuclide-commons` - it may be conflicting (though this will be fixed soon).

**Comment by jayallen** [comment]
Wouldn't you know, that fixed it!  Thanks!  I'll resolve the other bug I just filed too.
