### ISSUE TITLE
Uncaught Error: Cannot find module 'nuclide-commons-atom/create-pane-container'

### ISSUE THREAD

**Issue by jayallen** [facebook-atom/atom-ide-ui#236]
With any file open, choose View > Toggle Debugger.  Happens every time.  Given this and the very similar issue I submitted previously (#235), I'm thinking I may have a borked atom-ide-ui installation or something.

I'm tempted to uninstall and reinstall to see if it fixes the problem, but I'll hold out a few more days to see if I can figure out the issue.

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.12.6
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.11.1

### Stack Trace

Uncaught Error: Cannot find module 'nuclide-commons-atom/create-pane-container'

```
At module.js:472

Error: Cannot find module 'nuclide-commons-atom/create-pane-container'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at _load_createPaneContainer (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-debugger/lib/ui/DebuggerLayoutManager.js:22:92)
    at DebuggerLayoutManager.showDebuggerViews (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-debugger/lib/ui/DebuggerLayoutManager.js:684:57)
    at /packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-debugger/lib/main.js:462:31)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:384:49)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:273:23)
    at HTMLElement.disposable.default.atom.commands.add (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-debugger/lib/main.js:479:23)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:384:49)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1347:25)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:339:53)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:197:7)
```

### Commands

```
  2x -7:21.9.0 core:move-to-top (input.hidden-input)
     -7:21.3.0 core:move-to-bottom (input.hidden-input)
     -7:20.9.0 core:move-to-top (input.hidden-input)
     -1:04.8.0 window:toggle-dev-tools (input.hidden-input)
     -1:04.5.0 datatip:toggle (input.hidden-input)
     -1:00.4.0 command-palette:toggle (input.hidden-input)
     -0:58.7.0 editor:consolidate-selections (input.hidden-input)
     -0:58.7.0 core:cancel (input.hidden-input)
     -0:55.9.0 github:toggle-github-tab (input.hidden-input)
     -0:53 editor:consolidate-selections (input.hidden-input)
     -0:53 core:cancel (input.hidden-input)
     -0:46 console:toggle (button.btn.github-CommitView-button.github-CommitView-commit)
  3x -0:42.7.0 linter-ui-default:toggle-panel (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:35.5.0 console:toggle (atom-pane.pane)
     -0:29.5.0 debugger:toggle (atom-pane.pane)
     -0:29.5.0 debugger:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
```

### Non-Core Packages

```
atom-easy-jsdoc 4.12.5 
atom-ide-ui 0.11.1 
atom-lorempixel 0.1.0 
atom-nodejs-snippets 2.1.1 
atom-typescript 12.4.1 
busy-signal 1.4.3 
duplicate-removal 0.1.3 
es6-javascript 1.0.0 
ide-css 0.3.0 
ide-json 0.2.1 
ide-php 0.7.14 
ide-python 0.9.2 
ide-standardjs 0.0.1 
ide-typescript 0.7.6 
ide-yaml 0.4.3 
intentions 1.1.5 
language-babel 2.85.0 
language-javascript-jsx 0.3.7 
language-markdown 0.25.1 
linter 2.2.0 
linter-eslint 8.4.1 
linter-js-standard 5.0.0 
linter-markdown 5.2.1 
linter-perl 0.8.2 
linter-perlcritic 2.1.0 
linter-stylelint 4.3.0 
linter-ui-default 1.7.1 
lorem 1.5.0 
lorem-ricksum 0.2.1 
markdown-scroll-sync 2.1.2 
node-debugger 1.10.1 
perltidy 4.0.0 
pipe 0.4.0 
prettier-atom 0.53.0 
project-manager 3.3.5 
react 0.18.0 
react-es6-snippets 0.3.0 
react-snippets 1.1.0 
sort-lines 0.18.0 
text-manipulation 0.6.0 
toggle-quotes 1.1.0 
```

**Comment by jayallen** [comment]
Problem seems to have been a corrupted cache or module install.  See [here](https://github.com/facebook-atom/atom-ide-ui/issues/64#issuecomment-332980384) for the fix.
