### ISSUE TITLE
Uncaught Error: Cannot find module './constants'

### ISSUE THREAD

**Issue by achagani** [facebook-atom/atom-ide-ui#242]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.11.2

### Stack Trace

Uncaught Error: Cannot find module './constants'

```
At module.js:472

Error: Cannot find module './constants'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.26.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.26.1/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.26.1/resources/app/src/native-compile-cache.js:66:33)
    at _load_constants (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-debugger/lib/main.js:31:49)
    at Object.shouldDisplay (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-debugger/lib/main.js:335:64)
    at ContextMenuManager.module.exports.ContextMenuManager.cloneItemForEvent (~/AppData/Local/atom/app-1.26.1/resources/app/src/context-menu-manager.js:181:25)
    at ~/AppData/Local/atom/app-1.26.1/resources/app/src/context-menu-manager.js:191:32
    at Array.map (native)
    at ContextMenuManager.module.exports.ContextMenuManager.cloneItemForEvent (~/AppData/Local/atom/app-1.26.1/resources/app/src/context-menu-manager.js:189:43)
    at ContextMenuManager.module.exports.ContextMenuManager.templateForEvent (~/AppData/Local/atom/app-1.26.1/resources/app/src/context-menu-manager.js:102:39)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (~/AppData/Local/atom/app-1.26.1/resources/app/src/context-menu-manager.js:203:33)
    at WindowEventHandler.handleDocumentContextmenu (~/AppData/Local/atom/app-1.26.1/resources/app/src/window-event-handler.js:257:44)
```

### Commands

```
     -0:24.7.0 core:paste (input.hidden-input)
     -0:23.1.0 core:backspace (input.hidden-input)
     -0:21.7.0 editor:consolidate-selections (input.hidden-input)
     -0:21.7.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atom-ide-ui 0.11.2 
build-cargo 2.0.0 
ide-r 0.1.7 
ionide-fake 1.2.2 
ionide-fsharp undefined 
ionide-fsi 2.1.3 
ionide-installer 1.4.0 
ionide-paket 2.2.6 
ionide-webview 1.0.3 
ionide-yeoman 2.0.0 
linter 2.2.0 
```

**Comment by hansonw** [comment]
Does this still repro after restarting Atom? You may have tried to use this right after the update - otherwise try the steps in #64 to clear Atom's compile caches.
