### ISSUE TITLE
Error: code ERR_STREAM_WRITE_AFTER_END

### ISSUE THREAD

**Issue by bastisawesome** [facebook-atom/atom-ide-ui#246]
### Description
I seem to be unable to install atom-ide-ui either through APM or Atom's built-in package manager.
Output from the command line:
```
(node:2198) ExperimentalWarning: The fs.promises API is experimental
Installing atom-ide-ui to /home/bast/.atom/packages ✗

npm ERR! code ERR_STREAM_WRITE_AFTER_END
npm ERR! write after end
```
From the log file:
```
1728 verbose stack Error [ERR_STREAM_WRITE_AFTER_END]: write after end
1728 verbose stack     at writeAfterEnd (_stream_writable.js:243:12)
1728 verbose stack     at PassThrough.Writable.write (_stream_writable.js:292:5)
1728 verbose stack     at PassThrough.Writable.end (_stream_writable.js:582:10)
1728 verbose stack     at ReadEntry.entry.on (/usr/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
1728 verbose stack     at ReadEntry.emit (events.js:187:15)
1728 verbose stack     at ReadEntry.emit (/usr/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
1728 verbose stack     at ReadEntry.[maybeEmitEnd] (/usr/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:249:12)
1728 verbose stack     at ReadEntry.end (/usr/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:162:27)
1728 verbose stack     at Unpack.[consumeBody] (/usr/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
1728 verbose stack     at Unpack.[consumeChunkSub] (/usr/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
1728 verbose stack     at Unpack.[consumeChunk] (/usr/lib/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
1728 verbose stack     at Unzip.(anonymous function).on.chunk (/usr/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
1728 verbose stack     at Unzip.emit (events.js:182:13)
1728 verbose stack     at Unzip.emit (/usr/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
1728 verbose stack     at Unzip.write (/usr/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:99:17)
1728 verbose stack     at Unzip.write (/usr/lib/node_modules/npm/node_modules/tar/node_modules/minizlib/index.js:284:29)
1729 verbose cwd /tmp/apm-install-dir-118415-2198-1auekr0.0vax
1730 verbose Linux 4.15.12-1-ARCH
1731 verbose argv "/usr/bin/node" "/usr/lib/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/bast/.atom/.apm/.apmrc" "--userconfig" "/home/bast/.atom/.apmrc" "install" "/tmp/d-118415-2198-15ybm1y.9rx2/package.tgz" "--runtime=electron" "--target=1.8.4" "--arch=x64" "--global-style"
1732 verbose node v10.1.0
1733 verbose npm  v6.0.1
1734 error code ERR_STREAM_WRITE_AFTER_END
1735 error write after end
1736 verbose exit [ 1, true ]
```

### Versions
OS: Linux 4.15.12-1-ARCH x86_64 GNU/Linux
Output from `atom --version`
```Atom    : 1.26.1
Electron: 1.8.4
Chrome  : 59.0.3071.115
Node    : 8.2.1
```
Output from `apm --version`
```
apm  1.19.0
npm  6.0.1
node 10.1.0 x64
atom 1.26.1
python 2.7.15
git 2.17.0
```

### Additional Details
* Installed packages (`apm ls --installed`):
* * atom-typescript@12.4.1
* * remote-sync@4.1.8

**Comment by hansonw** [comment]
See: https://github.com/atom/apm/issues/791
