### ISSUE TITLE
Uncaught TypeError: Cannot read property 'signatureHelpAt' of null

### ISSUE THREAD

**Issue by thosky** [facebook-atom/atom-ide-ui#254]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.1 x64
**Electron**: 1.7.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.12.0

### Stack Trace

Uncaught TypeError: Cannot read property 'signatureHelpAt' of null

```
At C:\Users\ThomasSkytte\.atom\packages\atom-ide-ui\node_modules\rxjs\bundles\Rx.min.js:34

TypeError: Cannot read property 'signatureHelpAt' of null
    at SignatureHelpProvider.module.exports.SignatureHelpProvider.getSignatureHelp (/packages/php-ide-serenata/lib/SignatureHelpProvider.coffee:92:48)
    at /packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-signature-help/lib/SignatureHelpManager.js:204:23)
    at a._tryNext (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:104:348)
    at a._next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:104:250)
    at a.notifyComplete (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:106:6)
    at a._complete (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:90:245)
    at a.complete (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:68:52)
    at /packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:33:494
    at <anonymous>
```

### Commands

```
  4x -2:44.8.0 core:backspace (input.hidden-input)
  4x -2:32.3.0 core:confirm (input.hidden-input)
     -0:47.5.0 core:delete (input.hidden-input)
  2x -0:33.4.0 core:backspace (input.hidden-input)
     -0:23 core:move-down (input.hidden-input)
     -0:22.1.0 core:move-up (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.12.0 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
busy-signal 1.4.3 
color-picker 2.3.0 
docblockr 0.13.7 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.21 
git-plus 7.10.2 
highlight-selected 0.13.1 
ide-php 0.7.14 
intentions 1.1.5 
linter 2.2.0 
linter-php 1.5.1 
linter-ui-default 1.7.1 
minimap 4.29.8 
monokai 0.24.0 
php-server 0.8.0 
platformio-ide-terminal 2.8.1 
project-manager 3.3.5 
remote-ftp 2.2.0 
teletype 0.13.2 
todo-show 2.3.0 
```

**Comment by jgebhardt** [comment]
Looks like the error is being thrown in the `php-ide-serenata` package. Try disabling that package if you keep encountering issues. Closing, since this issue is outside of Nuclide's purview.
