### ISSUE TITLE
Uncaught Error: Cannot find module '../../../../nuclide-commons/event'

### ISSUE THREAD

**Issue by mrfizzl3** [facebook-atom/atom-ide-ui#281]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.0 x64
**Electron**: 2.0.3
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.12.0

### Stack Trace

Uncaught Error: Cannot find module '../../../../nuclide-commons/event'

```
At C:\Users\David S\.atom\packages\atom-ide-ui\node_modules\rxjs\bundles\Rx.min.js:70

Error: Cannot find module '../../../../nuclide-commons/event'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.28.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.28.0/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.28.0/resources/app/src/native-compile-cache.js:66:33)
    at _load_event (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-code-highlight/lib/CodeHighlightManager.js:18:19)
    at /packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-code-highlight/lib/CodeHighlightManager.js:76:46)
    at a._next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:261:315)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a._next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:184:285)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a._next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:136:208)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a.x (/packages/atom-ide-ui/modules/nuclide-commons/observable.js:357:86)
    at later (/packages/atom-ide-ui/modules/nuclide-commons/debounce.js:27:23)
```

### Commands

```
     -4:19.7.0 snippets:expand (input.hidden-input)
     -4:19.7.0 editor:indent (input.hidden-input)
     -4:19.1.0 core:backspace (input.hidden-input)
     -4:17.1.0 core:move-right (input.hidden-input)
 14x -4:14.4.0 core:move-left (input.hidden-input)
     -4:11.1.0 core:backspace (input.hidden-input)
 14x -4:10.5.0 core:move-right (input.hidden-input)
  2x -4:07.0 core:move-left (input.hidden-input)
 13x -4:06.2.0 core:backspace (input.hidden-input)
     -4:00.1.0 autocomplete-plus:confirm (input.hidden-input)
  3x -3:59.1.0 core:move-right (input.hidden-input)
     -3:58.1.0 core:move-left (input.hidden-input)
     -3:55.2.0 core:backspace (input.hidden-input)
     -3:37.9.0 core:confirm (input.hidden-input)
  8x -3:10.8.0 core:backspace (input.hidden-input)
     -3:03.9.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-discord 1.6.1 
atom-ide-ui 0.12.0 
ide-css 0.3.0 
ide-html 0.4.2 
ide-python 1.0.0 
teletype 0.13.3 
```

**Comment by hansonw** [comment]
This seems like an installation issue. Could you try again after following the suggested steps in #64?

**Comment by mrfizzl3** [comment]
The commands recommended in #64 are for OS X. Do I just replace ``rm`` with ``apm``?

**Comment by hansonw** [comment]
No, you'll want to use the equivalent of `rm -rf` on Windows: https://stackoverflow.com/questions/97875/rm-rf-equivalent-for-windows

And instead of `~/.atom/packages/atom-ide-ui` it'd be `C:\Users\David S\.atom\packages\atom-ide-ui`.
