### ISSUE TITLE
Uncaught Error: No mouse event found. Do not invoke this command directly. If you did use the con...

### ISSUE THREAD

**Issue by showsky** [facebook-atom/atom-ide-ui#290]
**Atom**: 1.28.2 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.6
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.13.0

### Stack Trace

Uncaught Error: No mouse event found. Do not invoke this command directly. If you did use the context menu, please report this issue.

```
At /Users/showsky/.atom/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-refactor/lib/main.js:138

Error: No mouse event found. Do not invoke this command directly. If you did use the context menu, please report this issue.
    at HTMLElement.Activation._disposables.atom.commands.add (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-refactor/lib/main.js:138:15)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:384:49)
    at Object.didConfirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:152:35)
    at SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:401:26)
    at HTMLDivElement.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:106:20)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
     -0:39.2.0 core:confirm (input.hidden-input)
     -0:39.2.0 nuclide-refactorizer:rename (input.hidden-input)
  2x -0:36.3.0 core:backspace (input.hidden-input)
  2x -0:35.6.0 core:undo (input.hidden-input)
     -0:26 command-palette:toggle (input.hidden-input)
     -0:24.9.0 core:paste (input.hidden-input)
     -0:23.9.0 core:move-down (input.hidden-input)
     -0:23.6.0 core:confirm (input.hidden-input)
     -0:23.5.0 nuclide-refactorizer:refactorize (input.hidden-input)
     -0:21.1.0 command-palette:toggle (input.hidden-input)
  7x -0:19.2.0 core:backspace (input.hidden-input)
     -0:16.8.0 core:paste (input.hidden-input)
  6x -0:15.7.0 core:backspace (input.hidden-input)
  2x -0:13 core:move-down (input.hidden-input)
     -0:12 core:confirm (input.hidden-input)
     -0:12 nuclide-refactorizer:refactorize-from-context-menu (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-ide-ui 0.13.0 
atom-monokai 0.10.9 
busy-signal 1.4.3 
goto-definition 1.3.4 
highlight-line 0.12.0 
highlight-selected 0.14.0 
hyperclick 0.0.0 
ide-json 0.2.1 
ide-php 0.7.14 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.7.1 
project-manager 3.3.6 
remote-ftp 2.2.0 
teletype 0.13.3 
```

**Comment by pelmers** [comment]
can you provide a bit more context? Did you trigger the item from the context menu?

**Comment by captbaritone** [comment]
Closing due to inactivity.
