### ISSUE TITLE
Atom ide diagnostics ui package failed to activate

### ISSUE THREAD

**Issue by ShailenNaidoo** [facebook-atom/atom-ide-ui#295]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.2 x64
**Electron**: 2.0.5
**OS**: Pop!_OS 18.04
**Thrown From**: [atom-ide-diagnostics-ui](https://github.com/facebook/nuclide) package 0.0.0

### Stack Trace

Failed to activate the atom-ide-diagnostics-ui package

```
At Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at StatusBarView.module.exports.StatusBarView.addLeftTile (/usr/share/atom/resources/app/node_modules/status-bar/lib/status-bar-view.js:69:28)
    at StatusBarTile.consumeStatusBar (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-diagnostics-ui/lib/ui/StatusBarTile.js:153:18)
    at Activation.consumeStatusBar (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-diagnostics-ui/lib/main.js:298:30)
    at /packages/atom-ide-ui/modules/nuclide-commons-atom/createPackage.js:64:34)
    at Provider.module.exports.Provider.provide (/usr/share/atom/resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.consume (/usr/share/atom/resources/app/node_modules/service-hub/lib/service-hub.js:50:24)
    at Package.activateServices (/usr/share/atom/resources/app/src/package.js:405:79)
    at Package.activateNow (/usr/share/atom/resources/app/src/package.js:233:20)
    at measure (/usr/share/atom/resources/app/src/package.js:206:33)
    at Package.measure (/usr/share/atom/resources/app/src/package.js:88:25)
    at activationPromise.Promise (/usr/share/atom/resources/app/src/package.js:200:20)
    at new Promise (<anonymous>)
    at Package.activate (/usr/share/atom/resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:695:42)
    at FeatureLoader.updateActiveFeaturesNow (/packages/atom-ide-ui/modules/nuclide-commons-atom/FeatureLoader.js:250:23)
    at FeatureLoader.updateActiveFeatures (/packages/atom-ide-ui/modules/nuclide-commons-atom/FeatureLoader.js:235:10)
    at FeatureLoader.activate (/packages/atom-ide-ui/modules/nuclide-commons-atom/FeatureLoader.js:206:10)
    at Object.activate (/packages/atom-ide-ui/index.js:94:19)
    at Package.activateNow (/usr/share/atom/resources/app/src/package.js:230:33)
    at measure (/usr/share/atom/resources/app/src/package.js:206:33)
    at Package.measure (/usr/share/atom/resources/app/src/package.js:88:25)
    at activationPromise.Promise (/usr/share/atom/resources/app/src/package.js:200:20)
    at new Promise (<anonymous>)
    at Package.activate (/usr/share/atom/resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:695:42)
    at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:491:35
    at exit (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/usr/share/atom/resources/app/src/buffered-process.js:267:15)
    at bufferStream (/usr/share/atom/resources/app/src/buffered-process.js:288:15)
    at Socket.stream.on (/usr/share/atom/resources/app/src/buffered-process.js:164:13)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```

### Commands

```
  2x -8:59.1.0 core:backspace (input.hidden-input)
     -8:47.3.0 core:confirm (input.hidden-input)
     -7:15.8.0 core:save (input.hidden-input)
  3x -7:15.6.0 core:backspace (input.hidden-input)
  4x -7:11.9.0 editor:delete-to-beginning-of-word (input.hidden-input)
     -7:06.0 core:confirm (input.hidden-input)
  2x -4:00.9.0 editor:newline (input.hidden-input)
     -3:58.6.0 autocomplete-plus:confirm (input.hidden-input)
  9x -3:54.6.0 core:backspace (input.hidden-input)
     -3:52.7.0 core:save (input.hidden-input)
     -3:50.1.0 settings-view:open (input.hidden-input)
 21x -3:41.8.0 core:backspace (input.hidden-input)
     -3:36.8.0 core:confirm (input.hidden-input)
     -3:10.9.0 core:select-all (input.hidden-input)
     -3:10.7.0 core:backspace (input.hidden-input)
     -3:05.8.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
file-icons 2.1.22 
```

**Comment by hansonw** [comment]
Closing in favor of https://github.com/atom/status-bar/issues/86.
