### ISSUE TITLE
Uncaught TypeError: event.stopImmediatePropagation is not a function

### ISSUE THREAD

**Issue by connorbrinton** [facebook-atom/atom-ide-ui#296]
The following was performed in a python context, using `ide-python` and Palantir's Python language server. However, I believe the issue is general to `atom-ide-ui`.

1. Define a class and a subclass in separate files, both having a single shared function 
2. In a separate file, declare an instance of the superclass (subclass might work too) and invoke the function
3. Hover and use the hyperlink shortcut to prepare to jump using the function name
4. A suggestion list should appear
5. Click on one of the suggestions (I left the hyperlink key held down during this whole time)

It opens the function just fine, it just throws up an error.

I would guess that the following line is at fault, though that's just a guess. I'm pretty sure it's in this file though:
https://github.com/facebook-atom/atom-ide-ui/blob/83a4ec1babbc88163290bc15b11c76d93d1e4f8d/modules/atom-ide-ui/pkg/hyperclick/lib/SuggestionListElement.js#L180

**Atom**: 1.28.2 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.6
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.13.0

### Stack Trace

Uncaught TypeError: event.stopImmediatePropagation is not a function

```
At /Users/connor/.atom/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:17

TypeError: event.stopImmediatePropagation is not a function
    at SuggestionList._confirm (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/hyperclick/lib/SuggestionListElement.js:205:13)
    at Object.ia (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:15:131)
    at Object.invokeGuardedCallback (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:16:137)
    at Object.invokeGuardedCallbackAndCatchFirstError (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:16:249)
    at za (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:20:288)
    at Da (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:22:174)
    at Fa (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:22:335)
    at Ba (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:21:248)
    at Ia (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:24:79)
    at Ja (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:24:244)
    at Gd (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:88:254)
    at bi (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:222:195)
    at Wb (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:44:362)
    at Ld (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:89:372)
    at ei (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:223:108)
    at Kd (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:89:113)
```

### Commands

```
     -1:54.5.0 core:backspace (input.hidden-input)
     -1:54.3.0 editor:newline (input.hidden-input)
     -1:51.6.0 core:backspace (input.hidden-input)
     -1:51.4.0 editor:newline (input.hidden-input)
     -1:49.5.0 core:backspace (input.hidden-input)
     -1:49.3.0 editor:newline (input.hidden-input)
     -1:47.5.0 core:move-right (input.hidden-input)
  2x -1:47 core:backspace (input.hidden-input)
     -1:45.7.0 core:save (input.hidden-input)
     -1:36 core:select-all (input.hidden-input)
     -1:35.7.0 core:backspace (input.hidden-input)
     -1:01.9.0 core:close (input.hidden-input)
     -0:46.8.0 pane:show-next-item (div.github-FilePatchView.is-unstaged)
     -0:43.6.0 core:backspace (input.hidden-input)
     -0:43.1.0 core:save (input.hidden-input)
  2x -0:42.6.0 pane:show-next-item (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
file-icons 2.1.22 
ide-python 1.0.0 
platformio-ide-terminal 2.8.3 
python-indent 1.1.5 
```

**Comment by drmathochist** [comment]
Hi, Connor. Thanks for sending this in.
We've noticed a that some issues come up when using `ide-python` along with Nuclide's Python language support.  That said, you've given us a great place to start in case this is a more general issue that has nothing to do with that package itself; I'll see if I can repro without `ide-python` involved.

It looks like you're also trying to use Palantir's `python-language-service` package as well, which should replace most of the stuff in Nuclide's `nuclide-python` and `nuclide-python-rpcpackages`. You might try disabling those and see if that helps, since you're not using them anyway.

**Comment by mostafaeweda** [comment]
I could reproduce and identified the misuse of `stopImmediatePropagation` and replaced with `stopPropagation` in a fix that'll coming in the next `atom-ide-ui` release, cc @hansonw

**Comment by quarthex** [comment]
Given two simple files:

```c
/* test.h */
void foo();
```

```c
/* test.c */
#include "test.h"
void foo() {}
void bar() {
  foo();
}
```

Ctrl + clic on the `foo` symbol, within the C source lead to the initial issue.
Please reopen.

**Atom**: 1.32.2 x64
**Electron**: 2.0.9
**OS**: Windows 7
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.13.0


### Stack Trace

Uncaught TypeError: event.stopImmediatePropagation is not a function

```
At C:\Users\rdeoux\.atom\packages\atom-ide-ui\node_modules\react-dom\cjs\react-dom.production.min.js:17

TypeError: event.stopImmediatePropagation is not a function
    at SuggestionList._confirm (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/hyperclick/lib/SuggestionListElement.js:205:13)
    at Object.ia (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:15:131)
    at Object.invokeGuardedCallback (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:16:137)
    at Object.invokeGuardedCallbackAndCatchFirstError (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:16:249)
    at za (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:20:288)
    at Da (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:22:174)
    at Fa (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:22:335)
    at Ba (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:21:248)
    at Ia (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:24:79)
    at Ja (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:24:244)
    at Gd (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:88:254)
    at bi (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:222:195)
    at Wb (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:44:362)
    at Ld (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:89:372)
    at ei (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:223:108)
    at Kd (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:89:113)
```

### Commands

```
  9x -8:28.7.0 core:select-left (input.hidden-input)
     -8:27.6.0 core:select-right (input.hidden-input)
     -8:25.2.0 core:confirm (input.hidden-input)
  3x -8:21.4.0 core:move-down (div.results-view.focusable-panel)
     -8:20.5.0 core:move-left (div.results-view.focusable-panel)
     -8:20 core:move-down (div.results-view.focusable-panel)
     -8:19.1.0 core:move-left (div.results-view.focusable-panel)
  3x -8:18.7.0 core:move-up (div.results-view.focusable-panel)
     -8:16.8.0 core:close (div.results-view.focusable-panel)
     -7:40.4.0 intentions:highlight (input.hidden-input)
     -7:40.1.0 symbols-view:toggle-file-symbols (input.hidden-input)
     -7:37.6.0 core:move-down (input.hidden-input)
     -7:37 core:confirm (input.hidden-input)
 98x -7:35.8.0 intentions:highlight (input.hidden-input)
     -0:21.8.0 core:close (input.hidden-input)
  2x -0:20.9.0 intentions:highlight (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ide-ui 0.13.0 
busy-signal 1.4.3 
color-picker 2.3.0 
convert-file-encoding 0.1.0 
docblockr 0.13.7 
editorconfig 2.2.2 
file-icons 2.1.26 
graphviz-preview-plus 1.5.5 
gruvbox-plus-syntax 1.3.1 
ide-clangd 0.4.0 
ide-python 1.0.0 
ide-rust 0.18.4 
intentions 1.1.5 
language-arm 1.2.3 
language-batch 0.4.0 
language-bnf 1.1.0 
language-cmake 1.1.0 
language-diff 0.7.0 
language-dot 1.7.0 
language-latex 1.2.0 
language-log 1.10.1 
language-lua 0.9.11 
language-restructuredtext 1.1.2 
language-rust 0.4.12 
latex 0.50.0 
linter 2.2.0 
linter-markdown 5.2.2 
linter-perl 0.8.2 
linter-pylama 0.10.1 
linter-ui-default 1.7.1 
minimap 4.29.9 
minimap-git-diff 4.3.1 
pdf-view 0.71.0 
permanent-delete 0.1.7 
pigments 0.40.2 
python-isort 0.0.7 
sort-lines 0.18.0 
svn 0.0.14 
symbols-tree-nav 0.15.5 
tortoise-svn 0.5.1 
```

**Comment by mattlyons0** [comment]
The reason this is still occurring is because there hasn't been a release since August. Notice the commit fixing this issue is not included in the latest tag: https://github.com/facebook-atom/atom-ide-ui/compare/v0.13.0...master

@hansonw seems to have stopped working on this project and they were the ones creating the releases. Does anyone know what the plan is for future releases?

**Comment by filipef101** [comment]
What can I do?
