### ISSUE TITLE
Uncaught Error: Cannot find module './DebuggerPaneViewModel'

### ISSUE THREAD

**Issue by srburk** [facebook-atom/atom-ide-ui#318]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.0 x64
**Electron**: 2.0.9
**OS**: Ubuntu 16.04.5
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.13.0

### Stack Trace

Uncaught Error: Cannot find module './DebuggerPaneViewModel'

```
At module.js:545

Error: Cannot find module './DebuggerPaneViewModel'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/static/<embedded>:11:154364)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:145671)
    at _DebuggerPaneViewModel (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-debugger/lib/ui/DebuggerLayoutManager.js:21:39)
    at pane.getItems.forEach.item (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-debugger/lib/ui/DebuggerLayoutManager.js:958:29)
    at Array.forEach (<anonymous>)
    at atom.workspace.getPanes.forEach.pane (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-debugger/lib/ui/DebuggerLayoutManager.js:957:23)
    at Array.forEach (<anonymous>)
    at DebuggerLayoutManager.hideDebuggerViews (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-debugger/lib/ui/DebuggerLayoutManager.js:956:31)
    at DebuggerLayoutManager.showDebuggerViews (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-debugger/lib/ui/DebuggerLayoutManager.js:777:10)
    at /packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-debugger/lib/main.js:584:31)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:345848)
    at CommandRegistry.dispatch (/usr/share/atom/resources/app/static/<embedded>:11:344323)
    at HTMLElement.atom.commands.add (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-debugger/lib/main.js:597:23)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:345848)
    at CommandRegistry.dispatch (/usr/share/atom/resources/app/static/<embedded>:11:344323)
    at AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app/static/<embedded>:1:650181)
    at EventEmitter.t (/usr/share/atom/resources/app/static/<embedded>:1:657565)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
  2x -0:37.2.0 window:toggle-full-screen (input.hidden-input)
     -0:24 tree-view:toggle (input.hidden-input)
     -0:16.4.0 console:toggle (div.tool-panel.tree-view)
     -0:10.9.0 debugger:toggle (div.tool-panel.tree-view)
     -0:10.9.0 debugger:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
ide-java 0.8.3 
```

**Comment by ebluestein** [comment]
Do you have a DebuggerPaneViewModel.js at /packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-debugger/lib/ui/? If not I wonder if the installation was corrupted somehow
