### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replaceWith' of undefined

### ISSUE THREAD

**Issue by simonepri** [facebook-atom/atom-ide-ui#32]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0-beta0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.3.1

### Stack Trace

Uncaught TypeError: Cannot read property 'replaceWith' of undefined

```
At /Users/simonepri/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:23

TypeError: Cannot read property 'replaceWith' of undefined
    at linterMessageV2ToDiagnosticMessage (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-diagnostics/lib/services/LinterAdapter.js:116:17)
    at linterMessagesToDiagnosticUpdate (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-diagnostics/lib/services/LinterAdapter.js:155:56)
    at /packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-diagnostics/lib/services/LinterAdapter.js:225:22)
    at a._next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:238:504)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:64)
    at a.notifyNext (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:60:68)
    at a._next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:61:263)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:64)
    at /packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:23:256
```

### Commands

```
     -7:25.2.0 core:confirm (input.hidden-input)
     -7:13.8.0 core:select-all (input.hidden-input)
     -7:13.6.0 core:paste (input.hidden-input)
     -7:13.3.0 core:confirm (input.hidden-input)
     -7:02.7.0 core:select-all (input.hidden-input)
     -7:02.5.0 core:paste (input.hidden-input)
  2x -5:55.6.0 core:close (input#linter-xo.fixOnSave.input-checkbox)
     -3:22.1.0 core:select-all (input.hidden-input)
     -3:21.7.0 core:cut (input.hidden-input)
     -3:19.9.0 core:paste (input.hidden-input)
     -3:19.2.0 core:backspace (input.hidden-input)
     -3:19 core:confirm (input.hidden-input)
     -1:28.3.0 core:select-all (input.hidden-input)
     -1:27.9.0 core:paste (input.hidden-input)
     -1:27.6.0 core:confirm (input.hidden-input)
     -0:22.7.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-ide-ui 0.3.1 
auto-update-packages 1.0.1 
config-import-export 0.3.1 
docblockr 0.11.0 
file-icons 2.1.11 
highlight-selected 0.13.1 
ide-java 0.6.0 
ide-typescript 0.6.1 
line-count 0.5.0 
linter-jsonlint 1.3.0 
linter-xo 0.23.1 
open-terminal-here 2.3.1 
project-manager 3.3.5 
Sublime-Style-Column-Selection 1.7.4 
sync-settings 0.8.3 
theme-switcher 1.1.0 
tree-view-git-status 1.4.0 
```

**Comment by Arcanemagus** [comment]
Looks like this is caused by `linter-xo` returning an empty Array of solutions [here](https://github.com/sindresorhus/atom-linter-xo/blob/ad52be47d18289c1b5a5e348ad9af618b4cabb68/lib/format.js#L40-L60).
