### ISSUE TITLE
Uncaught Error: Invariant violation: "oldElem.constructor.name === 'nuclide-react-mount-root'"

### ISSUE THREAD

**Issue by austintraver** [facebook-atom/atom-ide-ui#325]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.2 x64
**Electron**: 2.0.9
**OS**: Mac OS X 10.14.1
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.13.0

### Stack Trace

Uncaught Error: Invariant violation: "oldElem.constructor.name === 'nuclide-react-mount-root'"

```
At /Users/austintraver/.atom/packages/atom-ide-ui/modules/nuclide-commons-ui/ReactMountRootElement.js:67

Error: Invariant violation: "oldElem.constructor.name === 'nuclide-react-mount-root'"
    at /packages/atom-ide-ui/modules/nuclide-commons-ui/ReactMountRootElement.js:67:11)
    at /packages/atom-ide-ui/modules/nuclide-commons-ui/ReactMountRootElement.js:75:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146385)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149932)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:145675)
    at _ReactMountRootElement (/packages/atom-ide-ui/modules/nuclide-commons-ui/renderReactRoot.js:11:39)
    at renderReactRoot (/packages/atom-ide-ui/modules/nuclide-commons-ui/renderReactRoot.js:41:24)
    at Console.getElement (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-console/lib/ui/Console.js:423:67)
    at ViewRegistry.createView (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:322205)
    at ViewRegistry.getView (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:322067)
    at HTMLElement.getActiveView (/app.asar/src/pane-element.js:206:23)
    at HTMLElement.handleFocus (/app.asar/src/pane-element.js:44:25)
    at HTMLElement.activated (/app.asar/src/pane-element.js:115:12)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1186984)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1188425)
    at Pane.activate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:460854)
    at NotificationElement.t.exports.NotificationElement.removeNotificationAfterTimeout (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:887266)
    at NotificationElement.t.exports.NotificationElement.removeNotification (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:886152)
    at NotificationElement.t.exports.NotificationElement.handleRemoveNotificationClick (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:886269)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:882586)
```

### Commands

```
     -4:04.0 debugger:show-attach-dialog (div.)
  8x -4:00.6.0 core:backspace (input.hidden-input)
     -2:48.6.0 core:cancel (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui.teletype-Authenticated)
     -2:38.9.0 debugger:show-launch-dialog (atom-pane.pane.active)
 27x -2:18 core:backspace (input.hidden-input)
     -1:43 core:confirm (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui.teletype-Authenticated)
     -1:42.9.0 debugger:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui.teletype-Authenticated)
     -1:35.2.0 core:copy (atom-notification.error.icon.icon-flame.native-key-bindings.has-close)
     -1:03.3.0 debugger:show-launch-dialog (atom-notification.error.icon.icon-flame.native-key-bindings.has-close)
     -1:01.0 core:paste (input.hidden-input)
     -1:00.5.0 core:undo (input.hidden-input)
  4x -0:55.7.0 core:backspace (input.hidden-input)
     -0:45.1.0 core:confirm (input.hidden-input)
  9x -0:42.7.0 core:backspace (input.hidden-input)
     -0:31.8.0 core:confirm (input.hidden-input)
     -0:31.7.0 debugger:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui.teletype-Authenticated)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
ide-python 1.0.0 
nuclide 0.366.0 
script 3.18.1 
teletype 0.13.3 
```

**Comment by matthewwithanm** [comment]
Hey @atraverusc! This is happening because you have both Nuclide and Atom IDE UI installed, which isn't supported. Nuclide is a superset of Atom IDE UI so if you're using that, you can remove Atom IDE UI. Otherwise, uninstall Nuclide (:

**Comment by austintraver** [comment]
Thanks Matthew, I didn’t expect anybody to actually read this, let alone right me a response! That totally clears it up, thank you for your help!
