### ISSUE TITLE
Uncaught Error: Invalid message severity: error

### ISSUE THREAD

**Issue by narcopanda** [facebook-atom/atom-ide-ui#34]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0-beta0 x64
**Electron**: 1.6.9
**OS**: Ubuntu 17.04
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.3.2

### Stack Trace

Uncaught Error: Invalid message severity: error

```
At /home/sean/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:90

Error: Invalid message severity: error
    at getMessageFilterType (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-diagnostics-ui/lib/DiagnosticsViewModel.js:220:17)
    at diagnostics.filter.message (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-diagnostics-ui/lib/DiagnosticsViewModel.js:164:27)
    at Array.filter (native)
    at DiagnosticsViewModel._filterDiagnostics (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-diagnostics-ui/lib/DiagnosticsViewModel.js:163:24)
    at /packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-diagnostics-ui/lib/DiagnosticsViewModel.js:106:25)
    at a._tryProject (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:63:365)
    at a.notifyNext (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:63:254)
    at a._next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:61:263)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:64)
    at a._tryProject (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:63:438)
    at a.notifyNext (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:63:254)
    at a._next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:61:263)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:64)
    at a.notifyNext (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:60:68)
    at a._next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:61:263)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:64)
    at a._next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:106:294)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:64)
    at a.debouncedNext (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:148:434)
    at a.Eb (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:30:148)
    at a._execute (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:88:309)
    at a.execute (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:88:130)
    at a.flush (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:89:465)
```

### Commands

```
     -7:11.4.0 intentions:highlight (input.hidden-input)
     -7:11.1.0 core:save (input.hidden-input)
     -7:00.1.0 intentions:highlight (input.hidden-input)
     -6:59.8.0 editor:toggle-line-comments (input.hidden-input)
     -6:54.9.0 intentions:highlight (input.hidden-input)
     -6:54.6.0 core:save (input.hidden-input)
     -2:39.8.0 editor:newline (input.hidden-input)
  2x -2:33.9.0 core:backspace (input.hidden-input)
 10x -0:57.6.0 core:move-down (input.hidden-input)
     -0:56.4.0 core:move-up (input.hidden-input)
     -0:56 autocomplete-plus:confirm (input.hidden-input)
  2x -0:55.2.0 core:move-right (input.hidden-input)
     -0:53.2.0 editor:newline (input.hidden-input)
     -0:21 intentions:highlight (input.hidden-input)
     -0:20.8.0 core:save (input.hidden-input)
     -0:05.6.0 diagnostics:toggle-table (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-ide-ui 0.3.2 
autocomplete-clang 0.11.3 
autocomplete-java 1.2.7 
autocomplete-python 1.10.2 
busy-signal 1.4.3 
git-plus 7.9.3 
hyperclick 0.0.0 
ide-java 0.6.0 
ide-json 0.1.0 
intentions 1.1.5 
java-importer 1.4.1 
linter 2.2.0 
linter-clang 4.1.2 
linter-gcc 0.7.1 
linter-javac 1.9.4 
linter-python 3.1.2 
linter-ui-default 1.6.8 
monokai 0.24.0 
python-jedi 0.3.8 
```

**Comment by hansonw** [comment]
Hm... Looks like `linter-javac` uses non-standard types (besides the default 'Error' and 'Warning'): https://github.com/AtomLinter/linter-javac/blob/master/lib/init.coffee#L19

I guess @matthewwithanm's change to start enforcing the types is leading to this error. I'll harden the adapters in `modules/atom-ide-ui/pkg/atom-ide-diagnostics/lib/services/LinterAdapter.js` to ensure that the types match up.

**Comment by Arcanemagus** [comment]
@hansonw In the v1 API `type` was an open string (It just happened that almost all uses fit into `Error`, `Warning`, `Info`).

Under the v2 API `type` was removed and `severity` (optional under v1) was made required and turned into an `enum`.

**Comment by hansonw** [comment]
Makes sense. I made sure the message types get sanitized.
