### ISSUE TITLE
Failed to activate the multiples package

### ISSUE THREAD

**Issue by burhandodhy** [facebook-atom/atom-ide-ui#51]
### Before Submitting

* Have you installed an "ide-" language package? atom-ide-ui provides no functionality
  out-of-the box unless you've installed a suitable package.
Yes
* If your issue is language-specific, please file an issue against
  the "ide-" language package you're using instead.

### Description
On Package activation. Atom gives the following error
1) Failed to activate the atom-ide-busy-signal package
2) Failed to activate the atom-ide-code-actions package
3) Failed to activate the atom-ide-datatip packag
4) Failed to activate the atom-ide-definitions package
5) Failed to activate the atom-ide-diagnostics package

### Expected Behavior
Tell us what should happen.
It should be activated without any error.

### Actual Behavior
Tell us what happens instead.
Errors 

### Versions
* Atom: 1.21.0 beta1 64
* Client OS: Windows 10 64
* atom-ide-ui: 0.3.3

### Additional Details
* Installed packages (`apm ls --installed`):

├── aligner@1.2.4
├── aligner-javascript@1.3.0
├── aligner-php@1.2.0
├── atom-alignment@0.13.0
├── atom-autocomplete-plus-async-master@0.22.0
├── atom-ide-ui@0.3.3
├── atom-wordpress@0.3.0
├── auto-indent@0.5.0
├── autoclose-html@0.23.0
├── autocomplete-paths@2.11.0
├── autocomplete-php@0.3.7
├── autocomplete-wordpress-hooks@0.2.3
├── autocomplete-xml@0.9.4 (disabled)
├── autoprefixer@3.7.1 (disabled)
├── blade-snippets@0.2.0 (disabled)
├── busy-signal@1.4.3
├── cdn-libs@0.1.2
├── cson@2.0.1 (disabled)
├── docblockr@0.11.0
├── drag-drop-text@0.1.4
├── emmet@2.4.3
├── esformatter@2.3.0 (disabled)
├── file-icons@2.1.11
├── git-plus@7.9.3 (disabled)
├── goto-definition@1.3.4 (disabled)
├── highlight-line@0.12.0
├── ide-flowtype@0.17.4
├── ide-php@0.6.6
├── improved-autocomplete-php@1.1.1
├── intentions@1.1.5
├── javascript-snippets@1.2.1
├── jquery-snippets@11.0.0
├── jshint@1.8.6
├── language-babel@2.74.2 (disabled)
├── language-blade@0.34.0 (disabled)
├── laravel@0.7.1 (disabled)
├── laravel-5-snippets@0.8.0 (disabled)
├── laravel-forms-bootstrap-snippets@1.2.0 (disabled)
├── laravel-snippets@2.1.0 (disabled)
├── linter@2.2.0 (disabled)
├── linter-htmlhint@1.3.3 (disabled)
├── linter-jsonlint@1.3.0
├── linter-php@1.5.0
├── linter-phpcs@1.6.7 (disabled)
├── linter-ui-default@1.6.10
├── linter-xmllint@1.4.3 (disabled)
├── magento-tools@0.0.3 (disabled)
├── minimap@4.29.6
├── minimap-find-and-replace@4.5.2
├── minimap-git-diff@4.3.1
├── phpcbf@0.2.1
├── pretty-json@1.6.4 (disabled)
├── react@0.16.2 (disabled)
├── react-es6-snippets@0.3.0 (disabled)
├── react-snippets@0.9.0 (disabled)
├── simple-drag-drop-text@0.3.4
├── sort-lines@0.15.0
├── tabs-to-spaces@1.0.3
├── toggle-quotes@1.0.1
├── wordpress-api@1.2.2
├── wordpress-autocomplete@1.2.0
├── wordpress-snippet@0.0.0
├── wp-dev@0.3.5
├── wp-snippets@0.2.10
└── zp-acf-snippets@0.4.0 (disabled)

**Comment by hansonw** [comment]
Can you provide a screenshot or paste of the actual error?

**Comment by burhandodhy** [comment]
![screenshot_6](https://user-images.githubusercontent.com/7139602/30630303-6903a1e4-9df9-11e7-9b0c-5403e2fa8e41.jpg)

**Comment by hansonw** [comment]
Hmm.. can you try uninstalling/reinstalling the package and then reloading
Atom? It's also worth trying to clear the APM cache (~/.atom/apm).

**Comment by burhandodhy** [comment]
Already try both things but the problem remains there.

**Comment by hansonw** [comment]
Can you open the devtools console to see if there's any other errors?
(aside from "package not initialized"). It seems like some other package
may be failing during the initialization phase.

**Comment by burhandodhy** [comment]
Here is it

![screenshot_7](https://user-images.githubusercontent.com/7139602/30633333-ba2264ce-9e04-11e7-8663-8efaa97666c0.jpg)

**Comment by Mullazman** [comment]
Yep, same

**Comment by burhandodhy** [comment]
@hansonw any update ?

**Comment by vinimartinson** [comment]
same

**Comment by hansonw** [comment]
@Mullazman or @vinimartinson could you also try reloading Atom with the devtools console open (as in @burhandodhy) and send a screenshot from the errors at the very top? In @burhandodhy's screenshot I can see that the packages are failing to initialize but it's not showing the root cause :(

I'm kinda suspecting a conflict between atom-ide-ui and another Atom package. Following the steps in https://flight-manual.atom.io/hacking-atom/sections/debugging/, I wonder if you guys could try starting up from a clean `~/.atom` directory with *just* atom-ide-ui to try and narrow it down to some kind of conflict?

**Comment by alenb** [comment]
Having exact same issues with it. I've disabled all other packages, and only left atom-ide-ui, and it still throws the exact same errors. I've cleared apm and and reinstalled atom-ide-ui as well without any luck.

Here's a stack trace for one of them (they look all the same):

```
Error: Package not initialized
    at Object.moduleExports.(anonymous function) [as consumeBusySignal] (/Users/AlenBirindzic/.atom/packages/atom-ide-ui/modules/nuclide-commons-atom/createPackage.js:48:15)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.provide (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/service-hub.js:30:26)
    at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app/src/package.js:448:77)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:258:22)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:227:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:220:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:217:40)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:695:42)
    at _features.forEach.feature (/Users/AlenBirindzic/.atom/packages/atom-ide-ui/modules/nuclide-commons-atom/FeatureLoader.js:188:23)
    at Array.forEach (native)
    at FeatureLoader.activate (/Users/AlenBirindzic/.atom/packages/atom-ide-ui/modules/nuclide-commons-atom/FeatureLoader.js:186:20)
    at Object.activate (/Users/AlenBirindzic/.atom/packages/atom-ide-ui/index.js:102:21)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:255:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:227:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:220:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:217:40)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:695:42)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

**Comment by hansonw** [comment]
Hmm :( I've never been able to reproduce this across multiple platforms and
computers. Could you try:

1) Atom has several caches in ~/.atom (I think blob-store and compile-cache
mostly, though there may be others.) Try clearing those
2) Launch atom with --clear-window-state in case it's a problem with the
serialized state.

**Comment by Crystilia** [comment]
I am having the same issue. 

I've tried:
- Clearing all caches and reinstalling.
- Launching Atom with --clear-window-state.
- Reinstalling Atom 1.24.0.
- Going to the new beta version of Atom. 
- Installing on 2 different Windows 10 systems (same problem on both).
- Disabling all other packages.
- Running things as administrator and reinstalling.
- Installing different language packages.
- Today, updating to the newest atom-ide-ui. 
- A few more desperate and outlandish attempts that made no sense.

The errors all reference files under the AppData\Local\Atom\app-(version)\resources\app\ (file). 

However, in all my installations, these files are within an apm folder, which makes it seem like it should be looking at AppData\Local\Atom\app-(version)\resources\app\apm\ (file) instead. This could be my own ignorance of how it works, but it's the only thing that I noticed while attempting to solve the problem. If this is an issue with how I've installed Atom, I don't know how to fix it either.

Other than that observation, I have no idea how to fix it or why I'm running into the issue on two separate systems.
