### ISSUE TITLE
Uncaught Error: Couldn't convert text to a String

### ISSUE THREAD

**Issue by rerowep** [facebook-atom/atom-ide-ui#52]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.13
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.3.3

### Stack Trace

Uncaught Error: Couldn't convert text to a String

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:532

Error: Couldn't convert text to a String
    at TextBuffer.module.exports.TextBuffer.getText (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:532:94)
    at new ForwardsMultiLine (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/match-iterator.js:254:37)
    at TextBuffer.module.exports.TextBuffer.scanInRange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1028:28)
    at wordAtPositionFromBuffer (/packages/atom-ide-ui/modules/nuclide-commons/range.js:26:10)
    at wordAtPosition (/packages/atom-ide-ui/modules/nuclide-commons-atom/range.js:57:65)
    at HyperclickForTextEditor._onMouseMove (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/hyperclick/lib/HyperclickForTextEditor.js:198:64)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-ide-ui 0.3.3 
atom-python-virtualenv 0.14.0 
autocomplete-python 1.10.3 
busy-signal 1.4.3 
compare-files 0.8.1 
document-outline 1.6.1 
git-plus 7.9.3 
git-plus-toolbar 1.0.1 
ide-json 0.1.0 
ide-python 0.1.1 
intentions 1.1.5 
language-markdown 0.25.1 
linter 2.2.0 
linter-pylint 2.1.0 
linter-ui-default 1.6.10 
pp-markdown 0.0.2 
python-isort 0.0.7 
sort-lines 0.15.0 
split-diff 1.5.1 
tabs-to-spaces 1.0.3 
tool-bar 1.1.0 
trailing-spaces 0.4.0 
```

**Comment by hansonw** [comment]
This appears to be coming from within a core Atom API which shouldn't be throwing.
I found https://github.com/atom/atom/issues/15325 which has a very similar stack; maybe try chiming in there that it's still happening in 1.20.1? My guess is that it's caused by one of the other packages.
