### ISSUE TITLE
Uncaught TypeError: Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by q0022** [facebook-atom/atom-ide-ui#62]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0-beta1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'message' of undefined

```
At /Users/q0022/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:23

TypeError: Cannot read property 'message' of undefined
    at /packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-code-format/lib/CodeFormatManager.js:173:68)
    at a.error (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:136:232)
    at a._error (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:450)
    at a.error (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:144)
    at a.notifyError (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:60:132)
    at a._error (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:61:371)
    at a.error (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:144)
    at a._error (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:450)
    at a.error (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:144)
    at a.notifyError (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:60:132)
    at a._error (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:61:371)
    at a.error (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:144)
    at /packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:23:300
```

### Commands

```
     -0:38.1.0 core:paste (input.hidden-input)
     -0:10.6.0 code-format:format-code (div.lines)
```

### Non-Core Packages

```
atom-ide-ui 0.4.0 
busy-signal 1.4.3 
goto-definition 1.3.4 
highlight-selected 0.13.1 
ide-php 0.6.8 
intentions 1.1.5 
linter 2.2.0 
linter-php 1.5.1 
linter-ui-default 1.6.10 
svn 0.0.13 
symbols-tree-view 0.14.0 
```

**Comment by wivern-co-uk** [comment]
Issue persists

[Enter steps to reproduce:]

1. Open php file
2. Call context menu -> format code

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.1
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.5.1


### Stack Trace

Uncaught TypeError: Cannot read property 'message' of undefined

```
At /Users/wivern/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:23

TypeError: Cannot read property 'message' of undefined
    at /packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-code-format/lib/CodeFormatManager.js:173:68)
    at a.error (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:136:232)
    at a._error (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:450)
    at a.error (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:144)
    at a.notifyError (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:60:132)
    at a._error (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:61:371)
    at a.error (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:144)
    at a._error (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:450)
    at a.error (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:144)
    at a.notifyError (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:60:132)
    at a._error (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:61:371)
    at a.error (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:144)
    at /packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:23:300
```

### Commands

```
     -1:06.7.0 core:close (input.hidden-input)
     -0:54.9.0 pane:reopen-closed-item (input.hidden-input)
     -0:41.7.0 symbols-view:go-to-declaration (span.syntax--support.syntax--function.syntax--curl.syntax--php)
     -0:36.2.0 code-format:format-code (span.syntax--support.syntax--function.syntax--curl.syntax--php)
```

### Non-Core Packages

```
atom-ide-ui 0.5.1 
hex 0.6.2 
ide-php 0.6.9 
language-apache 1.7.0 
language-docker 1.1.8 
language-smarty 1.8.0 
lines 0.13.1 
```
