### ISSUE TITLE
Uncaught Error: Cannot find module './text-editor'

### ISSUE THREAD

**Issue by afcsantos** [facebook-atom/atom-ide-ui#64]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.13
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.4.0

### Stack Trace

Uncaught Error: Cannot find module './text-editor'

```
At /Users/andresantos/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:90

Error: Cannot find module './text-editor'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at _load_textEditor (/packages/atom-ide-ui/modules/nuclide-commons-atom/debounced.js:23:24)
    at /packages/atom-ide-ui/modules/nuclide-commons-atom/debounced.js:61:29)
    at a._next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:106:201)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:64)
    at a.debouncedNext (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:148:434)
    at a.Eb (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:30:148)
    at a._execute (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:88:309)
    at a.execute (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:88:130)
    at a.flush (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:89:465)
```

### Commands

```
     -1:52.2.0 core:delete (input.hidden-input)
  2x -1:49.2.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.4.0 
```

**Comment by hansonw** [comment]
We've usually found that this kind of issue is caused by a corrupt install and/or APM cache. could you try the following steps?

```
# remove the package
rm -rf ~/.atom/packages/atom-ide-ui
# remove the APM cache
rm -rf ~/.atom/.apm
# re-install atom-ide-ui
apm install atom-ide-ui
```

**Comment by afcsantos** [comment]
Thanks ;)
