### ISSUE TITLE
Failed to load the atom-ide-ui package

### ISSUE THREAD

**Issue by ArcherVI** [facebook-atom/atom-ide-ui#67]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.4.0

### Stack Trace

Failed to load the atom-ide-ui package

```
At Cannot find module 'babel-plugin-idx'

Error: Cannot find module 'babel-plugin-idx'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.20.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.20.1/resources/app/src/module-cache.js:354:58)
    at Function.require.resolve (~/AppData/Local/atom/app-1.20.1/resources/app/src/native-compile-cache.js:69:35)
    at /packages/atom-ide-ui-master/modules/nuclide-node-transpiler/lib/NodeTranspiler.js:48:14)
    at /packages/atom-ide-ui-master/modules/nuclide-node-transpiler/lib/NodeTranspiler.js:231:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.20.1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.20.1/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (~/AppData/Local/atom/app-1.20.1/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.20.1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-ide-ui-master/modules/nuclide-node-transpiler/lib/require-hook.js:29:24)
    at /packages/atom-ide-ui-master/modules/nuclide-node-transpiler/lib/require-hook.js:80:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.20.1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.20.1/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (~/AppData/Local/atom/app-1.20.1/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.20.1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-ide-ui-master/modules/nuclide-node-transpiler/lib/main.js:32:3)
    at /packages/atom-ide-ui-master/modules/nuclide-node-transpiler/lib/main.js:37:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.20.1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.20.1/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (~/AppData/Local/atom/app-1.20.1/resources/app/static/index.js:47:45)
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-ui 0.4.0 
java-generator 2.2.3 
```

**Comment by hansonw** [comment]
It looks like you're running from source, but the dependencies haven't been installed. Have you read the contributing docs?

https://github.com/facebook-atom/atom-ide-ui/blob/master/CONTRIBUTING.md

**Comment by jonyeezs** [comment]
[Enter steps to reproduce:]

Just installed the new version (0.5.3) from apm UI

**Atom**: 1.22.0-beta1 x64
**Electron**: 1.6.15
**OS**: Ubuntu 17.04
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.5.3

Did not run from source.

### Stack Trace

Failed to load the atom-ide-ui package

```
At Cannot find module './modules/nuclide-node-transpiler/lib/env'

Error: Cannot find module './modules/nuclide-node-transpiler/lib/env'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/usr/share/atom-beta/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom-beta/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/usr/share/atom-beta/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-ide-ui/index-entry.js:24:19)
    at /packages/atom-ide-ui/index-entry.js:31:3)
    at Module.get_Module._compile (/usr/share/atom-beta/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom-beta/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/usr/share/atom-beta/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom-beta/resources/app/src/package.js:903:35)
    at /usr/share/atom-beta/resources/app/src/package.js:158:34
    at Package.module.exports.Package.measure (/usr/share/atom-beta/resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (/usr/share/atom-beta/resources/app/src/package.js:144:18)
    at PackageManager.loadAvailablePackage (/usr/share/atom-beta/resources/app/src/package-manager.js:617:16)
    at config.transact (/usr/share/atom-beta/resources/app/src/package-manager.js:530:20)
    at Config.module.exports.Config.transact (/usr/share/atom-beta/resources/app/src/config.js:342:22)
    at PackageManager.loadPackages (/usr/share/atom-beta/resources/app/src/package-manager.js:528:23)
    at /usr/share/atom-beta/resources/app/src/atom-environment.js:821:34
```

### Commands

```
```

### Non-Core Packages

```
advanced-open-file 0.16.7 
aligner 1.2.4 
aligner-javascript 1.3.0 
aligner-ruby 1.6.1 
aligner-scss 1.3.1 
atom-beautify 0.30.5 
atom-ide-ui 0.5.3 
atom-material-ui 2.0.6 
atom-visual-studio-code-ui 1.3.4 
autoclose-html 0.23.0 
autocomplete 0.47.0 
autocomplete-emojis 2.5.0 
autocomplete-json 5.5.0 
autocomplete-modules 1.7.3 
autocomplete-paths 2.12.1 
build 0.69.0 
build-gulp 0.11.0 
build-npm-apm 0.12.0 
busy 0.7.0 
busy-signal 1.4.3 
change-case 0.6.5 
code-peek 1.4.21 
color-picker 2.2.5 
column-select 0.2.0 
docblockr 0.11.0 
double-tag 0.9.0 
editorconfig 2.2.2 
emmet-atom-plugin 0.0.1 
es6-javascript 1.0.0 
feedback 0.38.0 
file-icons 2.1.13 
fonts 3.0.3 
git-diff-details 1.4.0 
git-history 3.3.0 
git-line 0.6.0 
git-log 0.4.1 
highlight-selected 0.13.1 
hyperclick 0.1.5 
ide-csharp 0.6.0 
ide-typescript 0.6.2 
intentions 1.1.5 
language-batch 0.4.0 
language-cshtml 0.3.0 
language-diff 0.7.0 
language-ejs 0.4.0 
language-gherkin 1.0.4 
language-groovy 0.7.0 
language-nginx 0.8.0 
language-powershell 4.0.0 
language-puppet 0.23.0 
linter 2.2.0 
linter-eslint 8.4.0 
linter-raml 1.0.1 
linter-rubocop 2.2.0 
linter-scss-lint 3.1.1 
linter-swagger 0.4.2 
linter-ui-default 1.6.10 
merge-conflicts 1.4.5 
minimap 4.29.7 
minimap-bookmarks 0.4.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.1.3 
minitest-snippets 0.2.0 
new-moon-atom-syntax 2.0.9 
open-in-browser 0.5.2 
open-recent 5.0.0 
pretty-json 1.6.4 
raml 0.2.0 
ruby-block 0.3.6 
ruby-bundler 0.3.0 
seti-ui 1.9.0 
sync-settings 0.8.3 
todo-show 2.1.0 
trailing-semicolon 1.1.0 
xml-formatter 0.11.0 
```

**Comment by hansonw** [comment]
That file is definitely in the release. Please see https://github.com/facebook-atom/atom-ide-ui/issues/64

**Comment by Arcanemagus** [comment]
@djkago Please try the troubleshooting steps outlined in #64. This isn't an issue with your Atom version but your installation of `atom-ide-ui`.
