### ISSUE TITLE
Uncaught Invariant Violation: Minified React error #44; visit http://facebook.github.io/react/doc...

### ISSUE THREAD

**Issue by Meligy** [facebook-atom/atom-ide-ui#78]
[Enter steps to reproduce:]

1. Install atom-ide-ui
2. Install nuclide
3. All while having a TypeScript project open (.ts files)

**Atom**: 1.22.0-beta0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.13
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.4.0

### Stack Trace

Uncaught Invariant Violation: Minified React error #44; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=44 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

```
At /Users/Meligy/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:69

Invariant Violation: Minified React error #44; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=44 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at reactProdInvariant (/packages/atom-ide-ui/node_modules/react/lib/reactProdInvariant.js:32:15)
    at Object.findDOMNode (/packages/atom-ide-ui/node_modules/react/lib/findDOMNode.js:54:126)
    at elementRef (/packages/atom-ide-ui/modules/nuclide-commons-ui/addTooltip.js:51:38)
    at ref (/packages/nuclide/pkg/nuclide-file-tree/components/FileTreeEntryComponent.js:447:26)
    at commitAttachRef (/packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:170:173)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:180:233)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:183:408)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:184:367)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:188:412)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:187:423)
    at Object.enqueueSetState (/packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:140:182)
    at FileTreeSidebarComponent.v.setState (/packages/nuclide/node_modules/react/cjs/react.production.min.js:12:357)
    at /packages/nuclide/pkg/nuclide-file-tree/components/FileTreeSidebarComponent.js:376:482)
    at a.__tryOrUnsub (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:43:337)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:42:227)
    at a._next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:393)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:64)
    at /packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:69:274
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-ui 0.4.0 
atom-light-ui-4k 0.30.1 
code-dark-syntax 0.5.0 
daylight-ui 0.2.2 
emmet-snippets-compatibility 1.0.6 
file-icons 2.1.12 
github-2016-syntax 1.2.0 
haxe-syntax-light 1.1.0 
ide-csharp 0.6.0 
ide-flowtype 0.17.4 
ide-typescript 0.6.1 
mac-github-syntax 1.3.9 
markdown-folder 0.5.0 
markdown-scroll-sync 2.1.2 
northem-light-atom-ui 2.1.1 
nuclide 0.259.0 
octocat-syntax 2.0.1 
piatto-light 2.0.2 
proton-light 0.2.0 
redmond-syntax 1.0.2 
redmond-ui 0.1.5 
visual-studio-code 0.4.0 
```

**Comment by hansonw** [comment]
When you have both nuclide and atom-ide-ui installed, atom-ide-ui gets disabled. Please report this issue over at https://github.com/facebook/nuclide instead - thanks!

**Comment by Meligy** [comment]
That's fine. Thanks a lot.

Just for the record / extra information. This report was created via Atom automatic error reporting (except for steps to reproduce of course).

Cheers,
