### ISSUE TITLE
Uncaught Error: Cannot find module './getModifierKeys'

### ISSUE THREAD

**Issue by catinsunshine** [facebook-atom/atom-ide-ui#85]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.5.0

### Stack Trace

Uncaught Error: Cannot find module './getModifierKeys'

```
At C:\Users\catin\.atom\packages\atom-ide-ui\node_modules\rxjs\bundles\Rx.min.js:43

Error: Cannot find module './getModifierKeys'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.21.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.21.0/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.21.0/resources/app/src/native-compile-cache.js:66:33)
    at _load_getModifierKeys (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-datatip/lib/DatatipManager.js:7165:29)
    at /packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-datatip/lib/DatatipManager.js:7468:49)
    at a.__tryOrUnsub (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:43:337)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:42:227)
    at a._next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:393)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40:64)
    at /packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:81:365)
```

### Commands

```
     -7:47.4.0 run-python-simply:toggle (ul.list-inline.tab-bar.inset-panel)
     -6:13 core:paste (input.hidden-input)
     -3:26.4.0 welcome:show (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.5.0 
atom-python-run 0.9.3 
autocomplete-python 1.10.3 
ide-python 0.2.1 
python-indent 1.1.2 
run-python-simply 0.1.1 
script 3.17.1 
```

**Comment by hansonw** [comment]
Can you try the steps outlined here to clear the APM cache/reinstall?

https://github.com/facebook-atom/atom-ide-ui/issues/64#issuecomment-332980384
