### ISSUE TITLE
Failed to load the atom-ide-ui package -  EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

### ISSUE THREAD

**Issue by joepio** [facebook-atom/atom-ide-ui#86]
Happens when opening atom.

**Atom**: 1.19.6 x64
**Electron**: 1.6.9
**OS**: Ubuntu 16.04.3
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.5.0

### Stack Trace

Failed to load the atom-ide-ui package

```
At Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".


EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

    at new Function (<anonymous>)
    at /packages/atom-ide-ui/index.js:6:16
    at /packages/atom-ide-ui/index.js:641:2)
    at /packages/atom-ide-ui/index.js:812:3)
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/opt/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (opt/atom/resources/app/static/index.js:47:45)
    at require (/opt/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-ide-ui/index-entry.js:29:18)
    at /packages/atom-ide-ui/index-entry.js:31:3)
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/opt/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (opt/atom/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/opt/atom/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/opt/atom/resources/app/src/package.js:887:35)
    at /opt/atom/resources/app/src/package.js:158:34
    at Package.module.exports.Package.measure (/opt/atom/resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (/opt/atom/resources/app/src/package.js:144:18)
    at PackageManager.module.exports.PackageManager.loadAvailablePackage (/opt/atom/resources/app/src/package-manager.js:565:22)
    at /opt/atom/resources/app/src/package-manager.js:479:25
    at Config.module.exports.Config.transact (/opt/atom/resources/app/src/config.js:321:22)
    at PackageManager.module.exports.PackageManager.loadPackages (/opt/atom/resources/app/src/package-manager.js:473:25)
    at /opt/atom/resources/app/src/atom-environment.js:810:34
```

### Commands

```
     -1:16 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
advanced-open-file 0.16.7 
atom-beautify 0.30.5 
atom-ide-ui 0.5.0 
atom-import-sort 3.3.0 
atom-json-editor 0.4.1 
atom-lupa 0.7.43 
atom-material-contrast-syntax 0.3.1 
autocomplete-json 5.5.0 
autocomplete-modules 1.7.2 
busy-signal 1.4.3 
chmod 0.1.1 
color-picker 2.2.5 
contrast-syntax 0.8.1 
contrast-ui 0.53.0 
custom-title 1.0.1 
dash 1.7.1 
docblockr 0.11.0 
emmet 2.4.3 
env-from-shell 0.3.0 
ficus-syntax 2.1.0 
file-icons 2.1.13 
git-blame 1.3.1 
git-control 0.9.0 
git-plus 7.10.0 
git-projects 1.17.0 
git-time-machine 1.5.9 
go-debug 1.5.2 
go-plus 5.5.5 
go-signature-statusbar 1.2.3 
goto-definition 1.3.4 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
hyperclick 0.1.5 
ide-flowtype 0.17.4 
ide-typescript 0.1.6 
intentions 1.1.5 
js-hyperclick 1.11.1 
js-refactor 0.7.5 
language-babel 2.75.1 
language-graphql 0.9.0 
language-haskell 1.14.3 
language-ini 1.19.0 
language-lua 0.9.11 
language-nginx 0.8.0 
language-ocaml 1.9.5 
language-rdf 0.5.0 
language-rust 0.4.12 
language-slim 0.6.0 
language-swift 0.5.0 
language-thrift 1.0.2 
linter 2.2.0 
linter-eslint 8.3.2 
linter-golint 0.3.0 
linter-golinter 1.2.2 
linter-jsonlint 1.3.0 
linter-sass-lint 1.8.2 
linter-swagger 0.4.2 
linter-ui-default 1.6.10 
local-history 4.3.0 
MagicPython 1.0.12 
markdown-preview-plus 2.4.10 
merge-conflicts 1.4.5 
minimal-syntax 0.22.0 
nice-index 1.0.5 
node-debugger 1.10.1 
nuclide 0.256.0 
nuclide-format-js 0.0.41 
open-terminal-here 2.3.1 
pretty-json 1.6.4 
project-manager 3.3.5 
react 0.16.2 
react-es6-snippets 0.3.0 
refactor 0.11.5 
ruby-slim 0.2.0 
script 3.17.1 
set-syntax 0.4.0 
sort-lines 0.18.0 
susave 0.4.0 
sync-settings 0.8.3 
tablr 1.8.3 
toggle-quotes 1.0.1 
tool-bar 1.1.0 
webbox-color 0.5.9 
zooce-syntax 1.0.1 
```

**Comment by hansonw** [comment]
Oops, looks like the published package contains test coverage information >_< I'll put out v0.5.1 to fix this.
