### ISSUE TITLE
Failed to load the atom-ide-ui package

### ISSUE THREAD

**Issue by pay6aul** [facebook-atom/atom-ide-ui#87]
Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
Hide Stack Trace
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
    at new Function (<anonymous>)
    at C:\Users\moul7\.atom\packages\atom-ide-ui\index.js:6:16
    at Object.<anonymous> (C:\Users\moul7\.atom\packages\atom-ide-ui\index.js:641:2)
    at Object.<anonymous> (C:\Users\moul7\.atom\packages\atom-ide-ui\index.js:812:3)
    at Module.get_Module._compile (C:\Users\moul7\AppData\Local\atom\app-1.19.3\resources\app\src\native-compile-cache.js:106:36)
    at Object.value [as .js] (C:\Users\moul7\AppData\Local\atom\app-1.19.3\resources\app\src\compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///C:/Users/moul7/AppData/Local/atom/app-1.19.3/resources/app/static/index.js:47:45)
    at require (C:\Users\moul7\AppData\Local\atom\app-1.19.3\resources\app\src\native-compile-cache.js:66:33)
    at Object.<anonymous> (C:\Users\moul7\.atom\packages\atom-ide-ui\index-entry.js:29:18)
    at Object.<anonymous> (C:\Users\moul7\.atom\packages\atom-ide-ui\index-entry.js:31:3)
    at Module.get_Module._compile (C:\Users\moul7\AppData\Local\atom\app-1.19.3\resources\app\src\native-compile-cache.js:106:36)
    at Object.value [as .js] (C:\Users\moul7\AppData\Local\atom\app-1.19.3\resources\app\src\compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///C:/Users/moul7/AppData/Local/atom/app-1.19.3/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (C:\Users\moul7\AppData\Local\atom\app-1.19.3\resources\app\static\<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (C:\Users\moul7\AppData\Local\atom\app-1.19.3\resources\app\src\package.js:887:35)
    at C:\Users\moul7\AppData\Local\atom\app-1.19.3\resources\app\src\package.js:158:34
    at Package.module.exports.Package.measure (C:\Users\moul7\AppData\Local\atom\app-1.19.3\resources\app\src\package.js:99:21)
    at Package.module.exports.Package.load (C:\Users\moul7\AppData\Local\atom\app-1.19.3\resources\app\src\package.js:144:18)
    at PackageManager.module.exports.PackageManager.loadAvailablePackage (C:\Users\moul7\AppData\Local\atom\app-1.19.3\resources\app\src\package-manager.js:565:22)
    at C:\Users\moul7\AppData\Local\atom\app-1.19.3\resources\app\src\package-manager.js:479:25
    at Config.module.exports.Config.transact (C:\Users\moul7\AppData\Local\atom\app-1.19.3\resources\app\src\config.js:321:22)
    at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\moul7\AppData\Local\atom\app-1.19.3\resources\app\src\package-manager.js:473:25)
    at C:\Users\moul7\AppData\Local\atom\app-1.19.3\resources\app\src\atom-environment.js:810:34

**Comment by hansonw** [comment]
This is fixed in 0.5.1.
