### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by zetaron** [facebook-atom/atom-ide-ui#96]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.5.1

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2387

TypeError: Cannot read property 'id' of undefined
    at TextEditorComponent.screenPositionForPixelPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2387:79)
    at TextEditorComponent.screenPositionForMouseEvent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1952:23)
    at HyperclickForTextEditor._getMousePositionAsBufferPosition (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/hyperclick/lib/HyperclickForTextEditor.js:315:38)
    at HyperclickForTextEditor._onMouseMove (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/hyperclick/lib/HyperclickForTextEditor.js:185:88)
```

### Commands

```
     -1:35.5.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
```

### Non-Core Packages

```
atom-clock 0.1.15 
atom-ide-ui 0.5.1 
atom-wallaby 1.0.21 
auto-detect-indentation 1.3.0 
busy-signal 1.4.3 
character-table 0.4.3 
file-icons 2.1.13 
hyperclick 0.0.0 
hyperclick-markdown 0.2.2 
ide-flowtype 0.17.4 
ide-typescript 0.6.2 
intentions 1.1.5 
js-hyperclick 1.11.1 
language-docker 1.1.8 
language-graphql 0.9.0 
linter 2.2.0 
linter-docker 0.2.1 
linter-js-standard-engine 2.1.0 
linter-js-yaml 1.2.8 
linter-ui-default 1.6.10 
minimap-pigments 0.2.2 
pigments 0.40.2 
project-manager 3.3.5 
react 0.16.2 
relative-numbers 0.8.0 
split-diff 1.5.1 
sync-settings 0.8.3 
todo-show 2.1.0 
tomorrow-night-eighties-syntax 1.0.2 
vim-mode-plus 1.11.2 
wakatime 7.0.3 
web-view 3.0.0 
```

**Comment by hansonw** [comment]
Could you file this issue on the Atom repo instead, as this coming from inside a core Atom API?

Historically these have been bugs that required Atom fixes (example: https://github.com/atom/atom/issues/15441) so it would be best to bring this to their attention. Thanks!
